### PR TITLE
Fix blink on the category page

### PR DESCRIPTION
**Pull request by andrzejewsky**
closes: https://github.com/DivanteLtd/vue-storefront/issues/4780

### CODE REVIEW

**Comment by Fifciu** [comment]
Please try it locally:
- Home -> Men -> Women
- Men -> Women -> Men

It still behaves weirdly sometimes.

**Comment by andrzejewsky** [comment]
@Fifciu yeah didn't commit my last changes, check now

**Review by Qrzy — APPROVED** [review]

**Review by lukasborawski — APPROVED** [review]

**Comment by Fifciu** [comment]
Now it looks fine - no blink anymore

**Review by Fifciu — APPROVED** [review]

**Comment by filrak** [comment]
The issue with persisted state for non-existing ctaegory (Men -> Kids) is still present but that's another issue ;)

**Pull request merged**
