### PR TITLE
Bugfix/too early hydration with urldispatcher

### PR DESCRIPTION
**Pull request by patzick**
### Related issues

 
Improvement for #3403 

### Short description and why it's useful

Fixes hydration issue caused by UrlDispatcher with a lock to prevent multiple dynamic route calculations.
Continue thread from #3403 

@adamjedlicka, @Darwex - guys please check if this solution solves the problem. Are you able to reproduce this now and have you seen performance gain? My impression is that the page loads faster with route lock.

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [x] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### CODE REVIEW

**Comment by adamjedlicka** [comment]
This fix doesn't seem to work for us. We are still getting the SSR error and now it's even worse. Before the only visible problem was duplicated footer. Now the whole client-side rendering stops working. Whole page is non-interactive and lazy-loaded components won't load at all.

I'm adding screenshot of the error: [https://i.imgur.com/ALmOSSR.png](https://i.imgur.com/ALmOSSR.png)

**Comment by Darwex** [comment]
BTW the previous fix wit LazyLoad was working guys, it made the website slower, but it worked :-)

**Comment by patzick** [comment]
@adamjedlicka, @Darwex that's really bad. Let's start with the clean storefront - do you experience the same issue when checkout just this branch?

**Comment by adamjedlicka** [comment]
@patzick No. It looks like it fixes the error for clean VSF (or greatly minimizes it's occurrence). I was unable to get the SSR error to happen even after about fifteen minutes of refreshing the category page.

I think It's not working on Dr. Max because of invalid HTML markup (like <p> inside of another <p>) or SSR renderer having problems with comments inside Vue HTML templates.

**Comment by patzick** [comment]
Okay, that's actually good. I think we could help you somehow with finding the problem in your template. Most cases it is related to cms blocks which are not <no-ssr> wrapped or as you said - some invalid HTML. It shouldn't be caused by the comments though.
Let us know if you need assistance on that, I'll merge this fix for 1.10.1

**Comment by Darwex** [comment]
Hi Guys.

Why was this PR merged? I Understand it may be fixes it on pure VSF but it does not fix it on Dr. Max project. I asked whether we could merge the previous one which fixes it on both, Dr. Max and clean VSF.

@patzick

**Comment by patzick** [comment]
@Darwex this solves an issue without slowing down the page (even probably with making faster TTI). We also discussed that matter also internally and I merged that in after @adamjedlicka confirmation. We didn't have any other reports from implementations. I think first of all we should take a look at yours and try to find the cause.

**Comment by Darwex** [comment]
Hi @patzick 

I understand that. But the first solution worked for both clean VSF and our project. So from our side, I do not consider it as fixed. What is it what we can do to fix it on our project then?

Thanks.

**Pull request merged**
