### PR TITLE
Fixed aspect ratio issue of product in detail page

### PR DESCRIPTION
**Pull request by cnviradiya**
### Related issues

closes #
https://github.com/DivanteLtd/vue-storefront/issues/3187

### Short description and why it's useful

- Fix aspect ratio of image in product detail page.

### Screenshots of visual changes before/after (if there are any)

**Before**
image

**After**
image

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [X] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [X] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [X] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [X] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by alinadivante** [comment]
Ok, now ratio is okay, but @cnviradiya you should also remember about _Preventing content reflow from lazy-loaded Images_
now we have unwanted effect that you can see in my video:
Loaded_image


this was fixed by this PR https://github.com/DivanteLtd/vue-storefront/pull/2925/files

**Comment by cnviradiya** [comment]
> Ok, now ratio is okay, but @cnviradiya you should also remember about _Preventing content reflow from lazy-loaded Images_
> now we have unwanted effect that you can see in my video:
> Loaded_image
> 
> this was fixed by this PR https://github.com/DivanteLtd/vue-storefront/pull/2925/files

It's because of their are two images behind the scene 
image

So, VSF first lost 310X300 image and after it's appear Big image that's why this unwanted issue happen.

**Comment by pkarw** [comment]
Thanks @cnviradiya! @alinadivante could you please retest?

**Comment by alinadivante** [comment]
@cnviradiya another problem with photos..  Take a look at the home page now:
image

**Comment by patzick** [comment]
> So, VSF first lost 310X300 image and after it's appear Big image that's why this unwanted issue happen.
> Don't know why use two images.

@cnviradiya this is for better experience - first we show placeholder, then we download low quality image, which is a little bit blurred; then we switch it to high quality image. We cannot have image jumping there.

@przspa please have this PR in mind and consult it with @cnviradiya if he needs an assistant with image component :)

**Comment by przspa** [comment]
@cnviradiya we must find solution to render stretched lower quality. 
I use aspect ration boxes pattern to do that but... product image can have different ratio (for us default size is 600x744 )
for example 
- https://next.storefrontcloud.io/gear/gear-3/sprite-foam-roller-22.html
- https://next.storefrontcloud.io/training/training-9/yoga-adventure-48.html
to fix this issue I think you must detect natural image size after lowerQuality was loaded and after change paddingBottom to real size

**Comment by przspa** [comment]
I think this bug was fixed in last commit https://github.com/przspa/vue-storefront/tree/bugfix/%233187. We need two behavior. One for heightnes photo and second for square and widthnes photo.

**Comment by przspa** [comment]
@cnviradiya thank's for you help 👍 we fixed this issue

**Comment by przspa** [comment]
@cnviradiya thank's for you help 👍 we fixed this issue

**Pull request closed without merging**
