### PR TITLE
Feature/1326 media gallery issue

### PR DESCRIPTION
**Pull request by nuovecode**
### Issues involved:
#1326 #1327 #1268

### Description:

Hi @pkarw! before merging this PR let's check together that all the scenarios are covered:

1. **Non configurable products**: The gallery shows the media_gallery
2. **Configurable products with mergeConfigurableChildren set to true**: It works as before (except for the bug #1268 fixed), the gallery shows the configurable media_gallery and the images of the simples grouped by the attribute configured in _variantsGroupAttribute_. When you click on a variant, the slide moves to the selected color
3. **Configurable products with mergeConfigurableChildren set to false**. If no variant is selected we see all the images in point 2, If a variant is selected we see all the images of the corresponding simple product, the image attributes are defined in the _gallery.imageAttributes_ configuration

###  Screenshot of passed e2e tests
schermata 2018-08-17 alle 16 29 52

There are no changes in UI

### CODE REVIEW

**Comment by nuovecode** [comment]
I proposed adding some configurations, also added to the documentation

**Comment by pkarw** [comment]
@vue-kacper please do the CR + merge after tests

**Comment by vue-kacper** [comment]
Tested scenerios:

1. Sample product **/p/24-MB03/crown-summit-backpack-3** - works fine
2. Sample product **/p/WH09/ariel-roll-sleeve-sweatshirt-1167/WH09** - works fine

3. Sample product **/p/WH09/ariel-roll-sleeve-sweatshirt-1167/WH09** - something is wrong

After updating config to:

```
      "gallery": {
        "variantsGroupAttribute": "color",
        "mergeConfigurableChildren": false,
        "imageAttributes": ["image","thumbnail","small_image"],
        "width": 600,
        "height": 744
      }
```

Scenerio 3 generates weid resoult - Photos are grouped acoring to colors but they are duplicated (triple the same black shirts photos, triple green and triple yellow ones)

bug

@nuovecode could you verify scenerio 3 problem on your side?

**Comment by nuovecode** [comment]
Hi @vue-kacper thanks for reviewing, that's because this product has the same image as main, thumbnail and small image. In this case the configuration should have been:

`"imageAttributes": ["image"]`

With this config:

`"imageAttributes": ["image","thumbnail","small_image"]`

I combine the value of all three attributes (image, thumbnail and small_image) in the gallery. I don't know this makes sense or is it anti-intuitive. What do you think?

**Comment by vue-kacper** [comment]
Aww make sense now :) It works great with single element in "imageAttributes" array. Thanks @nuovecode

**Comment by pkarw** [comment]
@vue-kacper Please do check the last thing if pictures work in offline mode (in that case single photo, from thumbnails list is used instead of gallery)

**Comment by vue-kacper** [comment]
@pkarw  Done testing - scenario 1,2 and 3 works in offline mode just like in public demo - only single thumbnail is available for whole gallery. This feature is ready for merge

**Comment by ymaheshwari1** [comment]
> Tested scenerios:
> 
> 1. Sample product **/p/24-MB03/crown-summit-backpack-3** - works fine
> 2. Sample product **/p/WH09/ariel-roll-sleeve-sweatshirt-1167/WH09** - works fine
> 3. Sample product **/p/WH09/ariel-roll-sleeve-sweatshirt-1167/WH09** - something is wrong
> 
> After updating config to:
> 
> ```
>       "gallery": {
>         "variantsGroupAttribute": "color",
>         "mergeConfigurableChildren": false,
>         "imageAttributes": ["image","thumbnail","small_image"],
>         "width": 600,
>         "height": 744
>       }
> ```
> 
> Scenerio 3 generates weid resoult - Photos are grouped acoring to colors but they are duplicated (triple the same black shirts photos, triple green and triple yellow ones)
> 
> bug
> 
> @nuovecode could you verify scenerio 3 problem on your side?

Hi, what is the correct way to solve the issue that the images are getting duplicated when changing the mergeConfigurableChildren to false?
Also, what is the use of defining three values inside the image_attributes in the gallery inside the config. As I know it is not used for any specific thing, Can you explain this?

Thank You

**Pull request merged**
