### PR TITLE
add et-EE.csv language files to core and default theme

### PR DESCRIPTION
**Pull request by alphpkeemik**
### Related issues
none

### Short description and why it's useful
Add et-EE.csv language files to core/i18n/resource/i18n/et-EE.csv and src/themes/default/resource/i18n/et-EE.csv based on en-US.csv files in that directories.

### Screenshots of visual changes before/after (if there are any)
none

### Which environment this relates to
- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)

### Contribution and currently important rules acceptance
- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by andrzejewsky** [comment]
@alphpkeemik hey, thanks for the PR! Please change base to `release/v1.11` we are going to add this in the upcoming release.

**Comment by alphpkeemik** [comment]
@andrzejewsky base changed to release/v1.11.

**Comment by andrzejewsky** [comment]
@alphpkeemik I think there are some changes that aren't yours, it's because sometimes changing the base on githib breaks the history, could you use rebase command to solve that? or you can create this PR again starting from `release/v1.11` - sorry.

**Comment by alphpkeemik** [comment]
@andrzejewsky sry forgot to change pull request base

**Pull request merged**
