### PR TITLE
Payment and shipping methods sync with Magento

### PR DESCRIPTION
**Pull request by akbarik**
https://github.com/DivanteLtd/vue-storefront/issues/691

### CODE REVIEW

**Comment by pkarw** [comment]
@akbarik great job; please add the `notification` after user selects any other method than `cashondelivery` to just notify that the work is underway for implementing the real payment methods as planned on https://github.com/DivanteLtd/vue-storefront/issues

**Comment by akbarik** [comment]
@pkarw, have you had a chance to test this PR yet?

**Comment by pkarw** [comment]
Not, yet I'll try to do this soon!

**Comment by pkarw** [comment]
@akbarik as we discussed on slack - in generall this is cool BUT we need to debug the network request multiplication + errors on empty cart (add to cart -> remove all products)

**Pull request merged**
