### PR TITLE
[WIP] Feature/config type

### PR DESCRIPTION
**Pull request by Michal-Dziedzinski**
### Short description and why it's useful

Types to default.json file. It should reduce the number of errors when creating own configuration file.

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [ ] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [ ] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [ ] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by filrak** [comment]
I think we can even add descriptions to those types that we currently have in docs to have even better DX when working with config
image

**Comment by patzick** [comment]
Yes! Definitely then we have very clear info about usage, there can also be examples etc, overall config is difficult, with good descriptions we support developers and they will love that.

I'd just suggest to add `...Config` to interfaces names, like `ApiConfig`, `ServerConfig`, `CartConfig` - then it's clear what is this interface for, otherwise it could be confusing that it's actual module od `Server`.

**Comment by pkarw** [comment]
We need to overlook the codebase + use this type everywhere where the config is being used @Michal-Dziedzinski

**Comment by pkarw** [comment]
@filrak what are the next steps here?

**Comment by patzick** [comment]
@Michal-Dziedzinski hey, are you planning to finish this one? It's not active a while so probably much changed since then.

**Comment by pkarw** [comment]
Closing due to long time of inactivity :(

**Pull request closed without merging**
