### PR TITLE
#858 - Integration with Intercom

### LINKED ISSUE #858: Integration with Intercom
It would be great if someone could develop an integration with https://www.intercom.com/.
This tool contains both livechat and marketing automation.

### PR DESCRIPTION
**Pull request by MikeSheward**
### Related issues
closes #858

### Short description and why it's useful
Intergration with the Intercom customer messaging platform for your Vue Storefront, just amend the intercom > app_id in the config file (eg, /config/default.json) and enable it in your modules index file (eg, /src/modules/index.ts) and then it's plug and play. Intercom account required (free tier is available)

### Screenshots of visual changes before/after (if there are any)
image

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance
- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by pkarw** [comment]
Wow, this is nice! I'm just wondering if You wouldn't like to move it to separate repo and publish to the marketplace - https://forum.vuestorefront.io/c/modules - for getting some better visibility?

**Comment by MikeSheward** [comment]
> Wow, this is nice! I'm just wondering if You wouldn't like to move it to separate repo and publish to the marketplace - https://forum.vuestorefront.io/c/modules - for getting some better visibility?

Yeah thats a great idea, i will get that done :)

Thanks, Mike.

**Comment by MikeSheward** [comment]
Ok, i've now moved it into it's own Repo, can you guys add this to the forum? https://github.com/develodesign/vsf-intercom

Thanks

**Comment by pkarw** [comment]
@MikeSheward Great Job! Will be posted shortly!

**Pull request closed without merging**
