### PR TITLE
Fix number of breadcrumbs depends on config settings

### LINKED ISSUE #4027: Breadcrumbs not considering "categoriesRootCategorylId"
## Current behavior

When setting categoriesRootCategorylId the breadcrumbs still show categories above that root category id

## Expected behavior

When setting categoriesRootCategorylId i would expect the breadrumbs not showing any category that lies above this root category.

## Steps to reproduce the issue

Set categoriesRootCategorylId to a lower category in level 2 or 3 for example. go to product page and check breadcrumbs

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser:  Chrome79.0.3945.130 (64-Bit)
- OS:  Windows 10
- Node:  10
- Code Version:  1.11

### PR DESCRIPTION
**Pull request by Michal-Dziedzinski**
### Related Issues

closes #4027 

### Short Description and Why It's Useful

The option to set the number of crumb levels has been fixed, now it is depending on the settings in the config file

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by grimasod** [comment]
Hi @Michal-Dziedzinski, there could be an issue with this. `categoriesRootCategorylId` is a Category ID value, not a Category level. But it's always been flawed, because IDs are not always in numerical order

**Comment by andrzejewsky** [comment]
@Michal-Dziedzinski please rebase. Remember when you want to fix a bug - please use hotfix branch as a base

**Comment by andrzejewsky** [comment]
@Michal-Dziedzinski changelog please :)

**Comment by Michal-Dziedzinski** [comment]
Closed due to uselessness, link to discussion: https://github.com/DivanteLtd/vue-storefront/issues/4027

**Pull request closed without merging**
