### PR TITLE
[WIP] Packages / Theme  / Cli

### PR DESCRIPTION
**Pull request by filrak**
### Related issues

https://github.com/DivanteLtd/vue-storefront/issues/2696

### Short description and why it's useful

This PR will be WIP for some time but I'm keeping it open  for everyone to see changes.

The main goals of this PR is making our repo a proper monorepo and setting up new theme as independent package . Next steps at the end. 

- [x] changing VS to proper lerma repo with packages inside `/packages` folder (old workspaces need to remain for backward compatibility
- [ ] properly manage dependencies between packages (include core as theme dependency)
- [x] publishing `@vue-storefront/cli` as one of our packages
- [x] setting up basic setup for new theme as independent NPM package
- [ ] adding StorefrontUI to theme
- [ ] making sure it's stable and backward-compatible 

Now there are 2 packages inside `packages` dir:
- `cli` - Vue Storefront cli
- `theme-capybara` - codename for Theme 2.0

## Next steps 

After mergin this PR I will proceed to separating VS Core and current default theme as independent packages too so VS can be (finally) installed as a bare npm dependency and themes will be a templates (starters). 

All of the changes are backward compatible ;)

Don't comment on code since it's extremely tough right now. Only the generał idea is up to discussion

### CODE REVIEW

**Comment by zimme** [comment]
If you were to publish the cli package as `@vue-storefront/create-app` then you should be able to run `npm init @vue-storefront/app` (and ofc `npx @vue-storefront/create-app`).

The reason `create-react-app` is named that way is so you can to do `npm init react-app`.

You could also publish the cli under `create-vue-storefront-app` so that `npm init vue-storefront-app` would be possible.

**Comment by filrak** [comment]
Todo for this week - error handling :)

**Comment by fancydev18** [comment]
Hi Filip,

May I ask please why a dedicated, custom CLI is better than relying on Vue CLI?
We love Vue CLI, especially the way one can setup a proxy in vue.config.js 

I was wondering if extending/plugging into Vue CLI would still be an option, to take advantage of what that provides. 
Thanks!

**Comment by filrak** [comment]
@fancydev18 We had this discussion and initially decided to make VS . avue-cli plugin but abandoned this idea. The list of reasons is pretty long. Here are the most important ones
1. We don't want to adjust our build into vue-cli. It requires a lot of work yet gives nothing in return
2. Most of vue-cli-service tools will not work anyway so it's not worth the effort for now


BUT, our cli is a first step to externalize VS as separate npm package. Once we're ready with this you can use it even on vue-cli app

**Comment by filrak** [comment]
@pkarw can I merge it as we discussed? (after resolving conflicts ofc)

**Comment by filrak** [comment]
@zimme I decided to go with `@vue-storefront/cli init` ;) Since CLI will be capable of a few more things i decided to keep it as one package

**Comment by zimme** [comment]
@filrak Sounds like a plan, I guess it's easy enough for someone to create a `create-vue-storefront-app` package later on that just calls `@vue-storefront/cli init`.

It would be nice if the bootstrapped project, when using the init command, would add the cli package as a dev dependency and add scripts in package.json that is using the cli tool. This way there would be no need to globally install the cli tool.

One would simply use `npx @vue-storefront/cli init`, and then just use yarn/npm to run the different cli functions. Much like react-scripts and kcd-scripts

**Comment by pkarw** [comment]
@filrak for me it's fine! Just not sure about putting the `theme-capybara` to the core at this stage (it's not ready and I'm just afraid of messing out the whole picture - like "what the heck is this capybara?" :))

Maybe just release the command line tool with 1.10 and add capybara later?

**Comment by pkarw** [comment]
@filrak I just wanted to kindly ask about the status in here?

**Pull request merged**
