### PR TITLE
Cart optimization can now be used regardless if entity optimization is enabled

### LINKED ISSUE #4198: Allow optimising checkout request even if entity optimization is not enabled
## Current behavior

VSF has two configuration entries related to optimising (reducing) the data in the product entities:

- `entities.optimize`
   - Limit the amount of attributes that get loaded from ES
- `entities.optimizeShoppingCart`
   - Limit the attributes that get included in the request when doing a checkout

Currently the latter can be used only if the first one is also enabled. See: https://github.com/DivanteLtd/vue-storefront/commit/c10910ed6f43229137e94cf2899b972159eb3fc8#diff-0ea097d7f413c052b03047909d3162a5R7

IMO this is a bug. I don't see a reason why the cart could not be optimised unless the ES queries are also optimised.

Or am I possibly missing something?

## Repository

https://github.com/DivanteLtd/vue-storefront/blob/v1.11.2/core/modules/cart/helpers/optimizeProduct.ts#L7

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

### PR DESCRIPTION
**Pull request by juho-jaakkola**
### Related Issues

closes #4198

### Short Description and Why It's Useful

It was possible to enable the cart optimization (limiting amount of attributes in the cart data) only if entity optimization (limiting amount of attributes received from the API) was enabled.

Now the cart optimization can be enabled independently.

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [x] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
This isn't really backwards compatible for sites that have had cart optimisation disabled just by disabling entity optimisation altogether.

Is it still fine to include this as a bug fix? I can also update the Upgrade notes if necessary.

**Comment by andrzejewsky** [comment]
@juho-jaakkola yeah, please update upgrade notes and as it's not really a bugfix - please change branch to develop

**Comment by juho-jaakkola** [comment]
Ok, will do

**Comment by juho-jaakkola** [comment]
- [x] Upgrade notes added
- [x] Target branch set to `develop`

**Pull request merged**
