### PR TITLE
(Hard)Core training materials

### PR DESCRIPTION
**Pull request by pkarw**
### Related issues

Vue Storefront is getting more and more popular with more than 20 sites running on production. By the same time, the VSF Framework evolves with each new release and the docs are hardly trying to follow! 

These training materials are a set of Chief-recipes, experiences learned from the trenches. I’m trying to answer how to run Vue Storefront on production, troubleshoot most of the common problems and explain all the hidden features of Vue Storefront that can help you scale the application and solve most common issues.

**Feel free to add new topics in the comments**. I'll try to elaborate ;)

### CODE REVIEW

**Comment by jonathanribas** [comment]
@pkarw, can you add yours also please? :)

**Comment by kkdg** [comment]
Love this format! Live advice from the core people is valuable than anything. I will also work on my part regarding this issue. Thanks!

**Comment by pkarw** [comment]
Thanks @kkdg, you’re the best

**Comment by pkarw** [comment]
Merged to the docs by Degi already

**Pull request closed without merging**
