### PR TITLE
Feature/2633

### PR DESCRIPTION
**Pull request by bartdominiak**
### Related issues

#2633

### Short description and why it's useful

Updated vue-offline with babel

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by bartdominiak** [comment]
I've one issue with `Reason: ReferenceError: window is not defined.` Please don't marge it before @filrak approval

**Comment by filrak** [comment]
@bartdominiak check with 2.0.8

**Comment by patzick** [comment]
@bartdominiak could you check it with onlineHelper?
`import { onlineHelper } from '@vue-storefront/core/helpers'`
and then `onlineHelper.isOnline`

**Comment by patzick** [comment]
@bartdominiak are you willing to get back to this PR?

**Comment by pkarw** [comment]
Closing due to long inactivity

**Comment by bartdominiak** [comment]
Sorry for my inactivity. I'll be back to this PR ASAP.

**Pull request closed without merging**
