### PR TITLE
Catalog products sorting

### LINKED ISSUE #671: Add 'Sort by' feature
In design of category page we have 'Sort by …' select.
image
We should create this select with logic and add options like:
- Price: low to high
- Price: high to low
- Newest
- *Popularity
- *On sale: show first

### PR DESCRIPTION
**Pull request by kruchy8**
should be reviewed

Fixes #671

### CODE REVIEW

**Comment by pkarw** [comment]
This feature (sorting) should work with ElasticSearch - sorting server side (not client's side). I can help You with refactoring the code - please attach the screenshots of the UI provided. I'll use the provided UI and refactor the data logic. Thanks!

**Comment by nuovecode** [comment]
Hi @pkarw, 
I've done this on my project. I've added a global event in the SortBy component and on this event in the Category page I've added something like:

```
    onSortOrderChanged (sortby, direction) {
      this.$store.state.category.current_product_query = Object.assign(this.$store.state.category.current_product_query, {
        sort: sortby + ':' + direction,
        searchProductQuery: buildFilterProductsQuery(this.category, this.filters.chosen)
      })
      this.$store.dispatch('category/products', this.$store.state.category.current_product_query).then((res) => {
      }) 
    }
```
I don't know if it's the best approach, if you like it i can do a PR

**Comment by pkarw** [comment]
@nuovecode Yes, this is how it should have been done. Please prepare clear PR with UI + this query and I'll merge it

**Comment by nuovecode** [comment]
ook

**Pull request closed without merging**
