### PR TITLE
[#1227] Add base select component and replace country select

### PR DESCRIPTION
**Pull request by mercs600**
Ok I created base select component based on other base form components. I noticed that we can refactore these components because a lot of code responsible for UI is duplicated -> next time. 

zrzut ekranu 2018-06-02 o 14 50 17

### CODE REVIEW

**Comment by filrak** [comment]
GJ ;> Please write the docs for this component. new components without docs will not be merged

**Comment by pkarw** [comment]
@mercs600 are You willing to do the docs as Filip requested?

**Comment by pkarw** [comment]
OK, docs are required, the feature itself is fine :)

**Comment by pkarw** [comment]
@filrak it seems like @mercs600 doesn't have time to write the docs; the feature is quite important; could You please test it before the merge and then do just merge it in? We'll add docs later on ..

I know I know ..

**Pull request merged**
