### PR TITLE
Add validation message for city field

### PR DESCRIPTION
**Pull request by dz3n**
### Related issues
#3723 

### Short description and why it's useful
Add validation message for city field

### Screenshots of visual changes before/after (if there are any)
Screenshot at 2019-10-18 15-44-47

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [X] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [X] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [X] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by ArturDivante** [comment]
Hi! @dz3n - function works fine and validation is ok, we just need less technical, more user-friendly message. please change current message to:

**Comment by dz3n** [comment]
The message is changed

**Comment by ArturDivante** [comment]
Thank you. Message is now ok. However it turns out, there will be more things to address in this task, as city field appears in more than one place. 

1. Exactly as in shipping address, it should be adjusted one step further, in billing address section. Behavior described in original ticket (unclickable button without validation message)  occurs there as well. 
2. This is bit more complex - address may also be input from my account section (for logged in user), again in 2 places:
 A: My account > My profile > I have a company (...) - checkbox
 B: My account > My shipping details. 
Addresses from those 2 places are imported automaticaly during checkout, so incorrect inputs there will also trigger described problem. What is more, those 2 places in my account don't have city field validation at all (except non-empty). It needs to be applied there, same way as in checkout itself

**Comment by andrzejewsky** [comment]
@dz3n So, please apply validation for each occur of the city field, where @ArturDivante has noticed this issue, thanks!

**Comment by dz3n** [comment]
Added all missing validation messages I found

**Comment by ArturDivante** [comment]
All described paths tested, every mentioned place fixed. Good job! :)

**Pull request merged**
