### PR TITLE
Breadcrumbs Filter and Component fixes

### PR DESCRIPTION
**Pull request by grimasod**
### Related issues

closes #

### Short description and why it's useful

Fixes multiple Breadcrumb issues that are new in v1.11

1. Issues with the Breadcrumb Category filters: there are cases when categories have already been loaded and saved to the category map, but do not match with the breadcrumb filters. In these cases we need to run the category search query without using the category map.

A specific example is Magento's "Default Category". Often every product belongs to this category, but it may not be wanted in the breadcrumbs. It can be excluded by turning off "Include in menu" and adding `"breadcrumbFilterFields": { "include_in_menu": true }` to the config. This fix is required for this behavior to work correctly.

2. Breadcrumbs on non-catalog pages: The "routes" prop on the Breadcrumbs component had been removed from pages like Compare and My Account, as they only need the new "with-homepage" prop and the existing "active-route" prop. But without the "routes" prop, the catalog breadcrumbs can appear where they shouldn't, so the "routes" prop needs to be restored.

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [x] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by grimasod** [comment]
Description updated. This PR now also fixes an issue with the Breadcrumbs component.

**Comment by andrzejewsky** [comment]
@grimasod I don't fully understand the second issue. When you pass an empty array to the routes you will get eg.` Homepage / Compare` instead of `Homepage / All / Women / Tops / Compare` always, no matter if you are on category page. So I don't thinks so it was an issue...

**Comment by grimasod** [comment]
@andrzejewsky Until now, it has always been `Homepage / Compare`, so I was just returning it to that.

In the example you give, it would make sense if we had just browsed the Tops category, but not in all cases. For example, if we added some bags to the Compare list and then looked at women's tops without adding any. On the Compare page, we would get `Homepage / All / Women / Tops / Compare`, even though only bags are displayed.

The other cases too:
- `Homepage / All / Women / Tops / Order confirmation`
- `Homepage / All / Women / Tops / My Account`
- `Homepage / All / Women / Tops / About Us`

Should be
- `Homepage / Order confirmation`
- `Homepage / My Account`
- `Homepage / About Us`

**Comment by pkarw** [comment]
I guess we need @patzick comment on this one

**Comment by andrzejewsky** [comment]
@grimasod ok I see, I could even reproduce it

**Pull request merged**
