### PR TITLE
Fixed bug around first setup of storeView state when SSR

### PR DESCRIPTION
**Pull request by ResuBaka**
The problem was that when you had set a defaultStoreCode it would be used
but he would not load the store config of this store. Which gets fixed by this PR.

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by lukeromanowicz** [comment]
QA - please test if in single store mode and multistore mode it still is working correctly with default settings. Maybe @alinadivante could take care of it? :)

**Comment by alinadivante** [comment]
Unfortunately I'm not able to test it now because there is problem with testing locally on branch. Here I reported issue #3259

**Comment by pkarw** [comment]
@alinadivante  how about the status? will you be able to test it now?

**Comment by alinadivante** [comment]
@pkarw It seems good.
When I change config to  `"multistore": true` and `"defaultStoreCode": "de"` and I open localhost:3000 page I have German translation (when  `"defaultStoreCode": "it"` - there is Italian translation).
For single store mode  `"defaultStoreCode"` does nothing.

**Comment by pkarw** [comment]
Thanks @alinadivante for checking it out and ofc. @ResuBaka in first place - for making this feature happened :)

**Pull request merged**
