### PR TITLE
new date formatter using dayjs

### LINKED ISSUE #3102: Date filter is ignoring the format parameter
## Current behavior

I'm trying to change the format of a date within a template using the `date` filter:
```
<p>{{ item.created_at | date('format as a parameter here') }}</p>
```

But the date filter is in fact not using the parameter at all:
https://github.com/DivanteLtd/vue-storefront/blob/d40ba3b958c26d77d2d4c98bdf403af1ffd19275/core/filters/date.js

And therefore the date is always returned in the same format (e.g. `25.6.2019, 11:50:32`).

## Expected behavior
I should be able to choose the format when using the filter.

## Steps to reproduce the issue
Try to pass any argument to the `date` filter within a template:
```
<p>{{ item.created_at | date('format as a parameter here') }}</p>
```
No matter what you pass in, nothing happens.

## Repository
The latest commit for the file in the current `master` branch: https://github.com/DivanteLtd/vue-storefront/blob/d40ba3b958c26d77d2d4c98bdf403af1ffd19275/core/filters/date.js

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Any
- OS: Any
- Node: Any
- Code Version: v1.9.1

### PR DESCRIPTION
**Pull request by grimasod**
### Related issues

closes #3102

### Short description and why it's useful

Date filter was not using format. Now uses dayjs, which allows for locale based formatting and can also take a coded string format.

### Screenshots of visual changes before/after (if there are any)

Before
image

After
image

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [x] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [ ] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by grimasod** [comment]
@patzick Here's the updated WIP PR, on a branch from the 1.10 RC
It's using standard imports, not lazy loaded. It includes all locales, which is obviously inefficient. It's not optimized yet either, as that might depend on getting the lazy loading technique. Thanks for your help!

**Comment by patzick** [comment]
thanks @grimasod ! When i started work on lazy loading locales i came up with an idea to load locale files with language change. So when we change language, then proper locale file is loaded.
Then we can use our date filter as we used to in synced way, i added fallback if for any reason locale is not there then we use default locale.
Please look at changes i've made and share your thoughts :)

**Comment by grimasod** [comment]
@patzick Very nice idea! It's the missing piece, so we no longer need to handle lazy-loading in the filter :)

**Comment by pkarw** [comment]
@patzick can we merge it in?

**Comment by patzick** [comment]
Yes, i wanted David to see it first:)
Merging

**Pull request merged**
