### PR TITLE
Issue #3486 fix broken unit tests

### LINKED ISSUE #3486: Core > Unit Tests > Broken Tests because of missing depenancy
## Current behavior

On running **Yarn test: unit**, 8 Unit Tests fail because of 

> Cannot find module '@vue-storefront/unit-tests/utils'.
> import { mountMixinWithStore } from '@vue-storefront/unit-tests/utils'

## Expected behavior

**Yarn test: unit** should complete all unit tests successfully

## Steps to reproduce the issue

Run **Yarn test: unit**

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser:  N/A CLI Test
- OS:  Ubuntu 18.04
- Node:  Node v8.10.0
- Code Version:  Develop Branch

## Additional information

Simple Fix. Dependencies have been moved to main repo. I will update the tests concerned to get them back to a working state. This will help progress on the other "Unit Tests" Taskings

### PR DESCRIPTION
**Pull request by David-Dorr**
### Related issues

closes #3486 

### Short description and why it's useful

Enables Unit Tests to use mountMixinWithStore, and mountMixin from test > unit > utils.

Instead of using "import" and relative paths, node "require" is used instead. This is to make allowances if the /core gets moved in the future. 

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by ResuBaka** [comment]
This is funny I just checked this and I don't have a problem with the newest develop branch to run the tests.

And I am not 100% sure why it should work for me without the changes from this PR.

Do I need to use npm to install all packages that it is broken? 

Maybe with some info I can help you to have them work for you without the changes from your pr.

**Comment by David-Dorr** [comment]
@ResuBaka 

My Dev set-up is the manual install using Docker, both for StoreFront and StoreFront-API. 
I also did a (local) amendment to the DockerFile to make a 'node_modules' volume, so that they would be visible to my IDE, and of course, to Jest. (Maybe this should be a new Issue...??)

Anyways, on checking the '@vue-storefront' node module, the unit-tests/utils directory is gone.
But the utils is now in the main repo. Hence, why I submitted this PR.

**Comment by pkarw** [comment]
@David-Dorr did you ran `yarn` first hand? It's creating the folders/links for virtual modules `@vue-storefront/*`; we can't run `npm install` we need to run `yarn install instead`

**Comment by David-Dorr** [comment]
Let me run some tests locally,
For example, delete the node_modules directory, re run the docker image, and try with yarn.. etc.

**Comment by David-Dorr** [comment]
I will close this Pull request.

This is not the correct solution. In short, there are some symlinks missing from the "@vue-storefront" node module when using the Docker installation

**Pull request closed without merging**
