### PR TITLE
Bugfix/fixing static links

### PR DESCRIPTION
**Pull request by MariaKern**
### Short description and why it's useful
The static links on the cms elements (banners for example) on homepage are wrong, since the urls of categories changed from "/c/women-20" to "/women/women-20" for example.
This issue is also in the slider and the MinimalFooter and in the banners of the "de" an "it" stores.

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [ ] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [ ] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by alinadivante** [comment]
For the "de" and "it" stores  - links like "/frauen/frauen-20"  doesn't work, I'm redirected to /page-not-found.
I think we should use always `women/women-20`.
For "de" store it should be → `de/women/women-20`, for "it" → `it/women/women-20`

Please, see how links look now for "de"/"it" stores:
1. Link from sidemenu (and there is no products found):

2. Link from banner on homepage (user is redirected to /page-not-found):

3. Link from breadcrumbs (user is redirected to /page-not-found):

**Comment by pkarw** [comment]
@alinadivante can you please create a new issue out of this one/

**Comment by alinadivante** [comment]
No problem. :)  And we will close this one ?

**Comment by pkarw** [comment]
this one is closed because it's pull request so I'm afraid we'll lose this issue having it just in the comment

**Comment by alinadivante** [comment]
@pkarw I reported it here: #3359

**Pull request merged**
