### PR TITLE
[WIP]: FIX: url's in promoted_offers

### PR DESCRIPTION
**Pull request by GrimLink**
### Short description and why it's useful
The url is wrong in the `../src/themes/default/resource/promoted_offers.json`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)

### CODE REVIEW

**Comment by andrzejewsky** [comment]
Hey, @GrimLink thanks for your PR. Could you change base to branch `release/v1.11` (instead of master)?

**Comment by andrzejewsky** [comment]
@GrimLink could you resolve the conflict? Try to rebase your branch with the `release/v.1.11`

**Comment by GrimLink** [comment]
@andrzejewsky I am marking this PR as WIP since someone also changed the url's
But to a double name.

```json
# Master
{
  "link": "/c/women-20"
}
# My Change
{
  "link": "/c/women"
}
# Current in v1.11
{
  "link": "/women/women-20"
}
```

I need to test which one is needed ->

**Comment by andrzejewsky** [comment]
@GrimLink sure, just let me know when you finish 👍

**Comment by GrimLink** [comment]
@andrzejewsky I am closing this branch for a cleaner PR directly started from the release/v1.11
So without all the changes that are found in the master branch.

My PR is still valid and found here -> https://github.com/DivanteLtd/vue-storefront/pull/3741 😉

**Pull request closed without merging**
