### PR TITLE
FIX cartID entity = null error

### LINKED ISSUE #2592: Cart token is not refreshed even when invalid
## Current behavior

Screenshot 2019-03-14 09 17 10

There are some certain situation where the current shopping cart (stored in the localStorage `shop/carts/current-cart-token`) is no longer valid. For example, the quote has been closed server side.

In this case the `shipping-methods` and `payment-methods`, `totals` all subsequent calls return an issue like `{"code":500,"result":"No such entity with cartId = null"}`

In this situation the solution is to clear the local storage - as after that the new shopping cart id will be retrieved.

We should re-create shopping cart (to get new token/id automatically).

An example on how can we recreate the cart:
https://github.com/pkarw/vue-storefront/blob/f90f64de9cb3ce02e0f5c92d6ceba51014a066ca/core/modules/cart/store/actions.ts#L662

## Steps to reproduce the issue

This issue is not occurring all the time - to be honest, it's pretty hard to recreate it. I used to have when I've logged in as a user after 5-6months of inactivity. The user account has some quote id assigned (like 5561) which has been no longer valid.

We can probably reproduce this issue by manually setting the `localStorage` key  `shop/carts/current-cart-token` to random value and testing the subsequent cart synchronization logic

### PR DESCRIPTION
**Pull request by michhy**
### Related issues

closes #2592

### Short description and why it's useful

The clear cart function on microcart creates cartID token error without the added line.

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [ x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [ x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [ x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by michhy** [comment]
Please ignore the first two commits and take the last one. 
Sorry this is really my first time, hopefully this is finally helping.

**Comment by pkarw** [comment]
@michhy please let me know if You have `config.orders.directBackendSync` set to true?

**Comment by michhy** [comment]
@pkarw , the whole function should be like this: 
`clear (context) {
    context.commit(types.CART_LOAD_CART, [])
    context.commit(types.CART_LOAD_CART_SERVER_TOKEN, null)
    if (rootStore.state.config.cart.synchronize && !rootStore.state.config.orders.directBackendSync) {
      rootStore.dispatch('cart/serverCreate', { guestCart: !rootStore.state.config.orders.directBackendSync }, {root: true}) // guest cart when not using directBackendSync because when the order hasn't been passed to Magento yet it will repopulate your cart
    } else {
      rootStore.dispatch('cart/serverCreate', { guestCart: true }, { root: true }) }
  },`

**Comment by pkarw** [comment]
I'm on it. It looks like this is not the right solution, the issue is related to async network calls probably. I'm on it

**Comment by michhy** [comment]
amazing! thank you!

**Pull request closed without merging**
