### PR TITLE
WIP: PWA module with Workbox 4.0

### PR DESCRIPTION
**Pull request by filrak**
### Related issues

closes https://github.com/DivanteLtd/vue-storefront/issues/2492

### Short description and why it's useful

Workbox allows us to make use of latest PWA features and manage them in more maintainable and easier way. It also provides a unified ecosystem of PWA modules.

Progress of migration from sw-precache to Workbox with it's newly released version 4.0. Please don't do any kind of review yet. It's opened just to see the progress ;)

TODO:
- [x] Move precache capabilities to Workbox plugin
- [ ] Move runtime caching capabilities to workbox routes
- [ ] Remove SW build step from `/build` folder
- [ ] Add possibility to modify SW config from the project `src`
- [ ] Use workbox-window to notify about updates

### CODE REVIEW

**Comment by pkarw** [comment]
@filrak any other features to be placed inside this module? I mean: is it "pwa" the best name for it? shouldn't be more specific like "sw" or "service-worker"?

**Comment by filrak** [comment]
i plan to have most of pwa-related stuff here (regarding service worker, aths etc) i think it'll be good to have everything in one place. It was heavly discussed in spartacus too and they agreed on the same idea

**Comment by lukeromanowicz** [comment]
PWA is a very broad subject and service workers are only part of it. By the book, `pwa` directory should contain not only offline browsing related scripts and SW, but also push notifications, hardware APIs (geolocalization, camera i.e. for scanning codes) etc. Does this fit what you have in mind @filrak?

**Comment by filrak** [comment]
It depends. Overally yes but please keep in mind that it's for core PWA functionalities so stuff like barcode scannner is a material for a separate module

**Comment by pkarw** [comment]
@filrak I've moved this one to 2.0-rc1 as it shows that we kind of stuck in the middle of forest :)

**Comment by filrak** [comment]
I'll make it from scratch later.

**Pull request closed without merging**
