### PR TITLE
OneSignal easy integration.

### LINKED ISSUE #2228: Make OneSignal integration
## Description

Create module integrating One Signal ( https://onesignal.com/ ) with Vue Storefront. It'll allow awesome service for Push Notifications
Feel free to ask me for details on slack if you have any questions

### PR DESCRIPTION
**Pull request by snovak7**
### Related Issues
closes #2228

### Short Description and Why It's Useful
OneSignal Web Push Notifications.

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by andrzejewsky** [comment]
@snovak7 whoaa! Like this!! nice work! One thing, I wonder whether this module should be loaded by default. Maybe it supposed to be loaded only when a configuration is set in the config? What do you think? Also would be nice to update the docs - simple information that's this for and how we can configure it

**Comment by snovak7** [comment]
@andrzejewsky It's like so, when there is { "oneSignal": { "appId": "[guid]" } } is minimum required, then the whole "oneSignal" key object is passed to OneSignal init function which is important. So the one needing the Module can configure OneSignal fully as by their documentation.

Module is loaded via javascript, and there is some issues which can arise, because of the way OneSignal wants to take over the service-worker, for that reason I added also the "built-in" service worker into input of "importScripts" of OneSignalSDK Worker javascripts as a fail-safe.

I took the HotjarModule as a reference.

**Comment by andrzejewsky** [comment]
@snovak7 Hey, sorry that you have to wait for so long time... 

>  So the one needing the Module can configure OneSignal fully as by their documentation.

Yes, but I meant that add some short information to our docs about there is such an integration; what is the config option to enable it + reference to their docs - otherwise no one will even know about this integration is available (you can add it here: https://github.com/DivanteLtd/vue-storefront/tree/master/docs/guide/integrations)

And please update the changelog.

**Comment by pkarw** [comment]
@snovak7 can you maybe move this to separate repo as a module?

**Pull request closed without merging**
