### PR TITLE
Remove unnecessary code from productCustomOption

### PR DESCRIPTION
**Pull request by cnviradiya**
### Related issues

closes #

### Short description and why it's useful

- Remove unnecessary code from the product custom option

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [X] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [X] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [X] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [X] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [X] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by ResuBaka** [comment]
Hi I think that this does not really bring an positive change as I need like ~5 times longer to get the new code than the old one. 

So maybe just use the old code and remove the commented code in it. Then it should be fine i think but that is only may view on this.

**Comment by cnviradiya** [comment]
> Hi I think that this does not really bring an positive change as I need like ~5 times longer to get the new code than the old one.
> 
> So maybe just use the old code and remove the commented code in it. Then it should be fine i think but that is only may view on this.

@ResuBaka & @pkarw 
I test it works fine
and for the condition also I've made one demo you may check

Ref.: https://codesandbox.io/embed/vue-template-cu76j

**Comment by ResuBaka** [comment]
The problem is not that it works more that is harder to read/understand what is happening there. 

When you want it like you have done it this would be a better way to write it I think.

```javascript
this.active = filterOption.id === this.id ? !this.active : false
```

I have not tested it but it should do the same. @cnviradiya

**Comment by cnviradiya** [comment]
> The problem is not that it works more that is harder to read/understand what is happening there.
> 
> When you want it like you have done it this would be a better way to write it I think.
> 
> ```js
> this.active = filterOption.id === this.id ? !this.active : false
> ```
> 
> I have not tested it but it should do the same. @cnviradiya

Yes, this code also behaves same

**Comment by pkarw** [comment]
OK, thanks

**Pull request merged**
