### PR TITLE
Remove redundant code related to content type

### LINKED ISSUE #5081: Remove redundant code related to request payloads
We are setting content-type=application/json from each places while calling TaskQueue.execute/queue method. I think its good to remove the redundant code and move them to task.ts getPayload method.

### PR DESCRIPTION
**Pull request by dixitdeepak**
### Related Issues

closes #5081

### Short Description and Why It's Useful

Remove redundant code related to content-type while calling TaskQueue.execute/queue method. Still if anyone want to override contentType can pass content-type header while calling TaskQueue method

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by Fifciu — CHANGES_REQUESTED** [review]
Very good idea! What do you think about applying the same for `mode: 'cors'`?

**Comment by dixitdeepak** [comment]
sounds good, I am also thinking to add Accept header as well in this PR

**Comment by Fifciu** [comment]
So would you like to add `Accept: application/json` to them? I am not sure if it is a good idea. 
- Please tell me why would you like to add it? 
- What are the benefits & possible disadvantages? 
- Do you see any potential future problems caused by Accept?

**Comment by dixitdeepak** [comment]
- Please tell me why would you like to add it?

While modifying code I found some reference where accept header value is set, eg. UserServices.ts, ReviewServicse.ts
As we are already using the Accept header at some place, so to make it consistent its good to have it at common place

- What are the benefits & possible disadvantages?

The Accept request-header field can be used to specify certain media types which are acceptable for the response. It tells the server which object types the client can handle
Server side api may return response based on request accept header type as well. 

https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

- Do you see any potential future problems caused by Accept?
 I can't imagine any potential future problem caused by Accept.

**Comment by Fifciu** [comment]
Ok, then let's implement this @dixitdeepak

**Comment by dixitdeepak** [comment]
@Fifciu Done

**Review by Fifciu — CHANGES_REQUESTED** [review]
Great job!

Please update changelog and we could merge it. However, I was thinking about this PR and I have another suggestion. What do you think about setting `payload.method` to `GET` by default? We could get rid of many `mode: 'GET'` then.

**Comment by dixitdeepak** [comment]
@Fifciu sounds good, Will update the PR with method = 'GET'

**Comment by dixitdeepak** [comment]
@Fifciu Done, I did git rebase, Please let me know if its looks good to you.

**Comment by dixitdeepak** [comment]
Closing the PR, as git rebase modified lots of files. 
Created new PR 
https://github.com/DivanteLtd/vue-storefront/pull/5209

**Pull request closed without merging**
