### PR TITLE
wait for translations messages while loading app

### LINKED ISSUE #3602: Translations issues in production mode
## Current behavior

When trying to translate strings taken from the query string, in custom theme components, the translation does not work in production mode. In dev mode, it works always.
If I try with hardcoded values, the translation works, but in this case, we need the string to be taken from the query.
Example code: `i18n.t(this.$route.query.newsletter)`

## Expected behavior

The query string value should be translated, also when in the production mode.

## Steps to reproduce the issue

1. go to this url in the browser: http://localhost:3000/?newsletter=Your%20subscription%20has%20been%20confirmed.
2. Try to take the newsletter query value on mounted, translate it and send a notification.
`  mounted () {
    this.newsletterCheck()
  }`

`        this.$store.dispatch('notification/spawnNotification', {
          type: 'success',
          message: i18n.t(this.$route.query.newsletter),
          action1: { label: i18n.t('OK') }
        })`
## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser:  Google Chrome Version 77.0.3833.0 (Offizieller Build) dev (64-Bit)
- OS:  MacOS Sierra 10.12.6
- Node:  10.15.1
- Code Version:

### PR DESCRIPTION
**Pull request by gibkigonzo**
### Related issues

closes #3602

### Short description and why it's useful

I don't know if waiting for locale messages is best solution, but now it can create race condition if `config.i18n.bundleAllStoreviewLanguages` is set on `false`. It doesn't wait for translations while loading app.

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pkarw** [comment]
@gibkigonzo this is cool; thanks for this however I belive that @ResuBaka has this issue with current master so we need to backport to 1.10.3 and release as 1.10.4 hotfix

@ResuBaka can you please confirm this solves the issue?

**Comment by pkarw** [comment]
@ResuBaka ok, I think that you should also apply this PR: https://github.com/DivanteLtd/vue-storefront/pull/3540 as it's fixing another race condition with url dispatcher/multistore. We're pretty close to RC1; should be released at Friday

**Comment by ivancukns** [comment]
Yes, I will test this today.

**Comment by pkarw** [comment]
Cool! @ResuBaka that's how "Priorities on Github" feature of "Production Package" works. 2h TTCI (Time To Close the Issue) ;)

**Pull request merged**
