### PR TITLE
Bugfix 2960 getSearchAdapter

### LINKED ISSUE #2960: getSearchAdapter always creates new instance for same adapterName
## Current behavior

If you call getSearchAdapter successively several times with the same adapterName, a new instance will be created each time.

## Expected behavior

If you call getSearchAdapter successively several times with the same adapterName, a new instance creates only once. Other calls should  return  existing instance.

## Repository

https://github.com/DivanteLtd/vue-storefront/blob/master/core/lib/search/adapter/searchAdapterFactory.js

line 10

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

### PR DESCRIPTION
**Pull request by bratok**
### Related issues

closes #2960 

### Short description and why it's useful
New instance will be saved into collection and returned form it

### CODE REVIEW

**Comment by patzick** [comment]
@bratok great improvement! Would you mind to add unit tests to cover this case?

**Comment by bratok** [comment]
@patzick Yes, I will do. It is in progress

**Comment by bratok** [comment]
Hi, i have create another pull request with unit tests 
https://github.com/DivanteLtd/vue-storefront/pull/3014

**Comment by pkarw** [comment]
Closing in favor of #3014

**Pull request closed without merging**
