### PR TITLE
[BUGFIX] Move 'Clear cart' button to the upper part of the window

### PR DESCRIPTION
**Pull request by rafalpyska**
### Related issues
#2697

### Short description and why it's useful
Move "clear cart" button to the top of the cart. Additionaly, I've added conditional to clear cart button because it was displaying when there was no products in the cart.

### Screenshots of visual changes before/after (if there are any)
before
after

### Which environment this relates to

Test version (bugfix to new feature).

### CODE REVIEW

**Comment by pkarw** [comment]
Thanks! I belive we should consult it with the UX designer as this button shouldn’t look like the main CTA which is Go To Cart in here

**Comment by StasiekDivante** [comment]
A "clear cart" button can have the same style as "return to shipping" one + additional remove icon. We use this style for button through the demo as a secondary button. 

To create visual clarity small 1px divider can be added beneath "shopping cart" header

Group

**Comment by pkarw** [comment]
Thanks, @StasiekDivante; @rafalpyska can You please adjust the styles?

**Comment by rafalpyska** [comment]
@pkarw Sure.

**Comment by pkarw** [comment]
@rafalpyska could You please provide us with the screenshots after changes?

**Comment by rafalpyska** [comment]
Zrzut ekranu 2019-04-24 o 13 35 50

Zrzut ekranu 2019-04-24 o 13 36 37

**Comment by rafalpyska** [comment]
@pkarw  I have added horizontal divider and decreased font size a little bit. But I see it's too late.

**Pull request merged**
