### PR TITLE
Feature/networks instead host mode

### LINKED ISSUE #4399: Use network instead of host mode
## What is the motivation for adding / enhancing this feature?
As mentioned in #3299 there is an issue with the current docker-compose configuration on OSX. I suggest to use external networks instead of the `network_mode: host`.

## What are the acceptance criteria 
* [ ] `network_mode: host` is removed fro the docker-compose.yml
* [ ] the api project network is added as external network to the docker-compose.yml

## Can you complete this feature request by yourself?
* [x] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [ ] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information
My suggested modifications:

```
version: '2.0'
services:
  app:
    # image: divante/vue-storefront:latest
    build:
      context: .
      dockerfile: docker/vue-storefront/Dockerfile
    env_file: docker/vue-storefront/default.env
    environment:
      VS_ENV: dev
# REMOVE this line
#    network_mode: host
    volumes:
      - './babel.config.js:/var/www/babel.config.js'
      - './config:/var/www/config'
      - './core:/var/www/core'
      - './ecosystem.json:/var/www/ecosystem.json'
      - './.eslintignore:/var/www/.eslintignore'
      - './.eslintrc.js:/var/www/.eslintrc.js'
      - './lerna.json:/var/www/lerna.json'
      - './tsconfig.json:/var/www/tsconfig.json'
      - './tsconfig-build.json:/var/www/tsconfig-build.json'
      - './shims.d.ts:/var/www/shims.d.ts'
      - './package.json:/var/www/package.json'
      - './src:/var/www/src'
      - './var:/var/www/var'
      - './packages:/var/www/packages'
    tmpfs:
      - /var/www/dist
# ADD this line
    networks:
      - vue-storefront-api_default
    ports:
      - '3000:3000'

# ADD this lines
networks:
  vue-storefront-api_default:
    external: true
```

### PR DESCRIPTION
**Pull request by tstrohmeier**
### Related Issues
- #4399

closes #4399

### Short Description and Why It's Useful
On OS X the current setup is not working as described in #3299. This change would be improve the current setup and use a external docker network in the docker compose specifcation

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [x] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by gibkigonzo** [comment]
@tstrohmeier can you please update your branch?

**Comment by tstrohmeier** [comment]
> @tstrohmeier can you please update your branch?

The version number?

**Comment by gibkigonzo** [comment]
@tstrohmeier sorry I should give you more info, please rebase it with branch `hotfix/v.1.11.4`. I've got message on gh `This branch is out-of-date with the base branch`. So I can't merge it.

**Comment by gibkigonzo** [comment]
Please make update with branch `hotfix/v1.12.2` :pray:

**Comment by pkarw** [comment]
Looks fine for me however it should be tested on MacOSX / Linux. My question is if it works well with the default “local host/api” endpoint set in the configs - will The VSF still be able to connect to these? we’ve got vsf-api up and running over this address and by default the same host for api is set for browser and server requests. I guess this “external” flag makes it attached to the default host network isn’t it? @tstrohmeier

**Comment by Fifciu** [comment]
I think we do not need to use external network. network_mode host does not work on other OSes than Linux. However, port mapping does - that's why only removing network_mode should solve a problem. I already tested it and merged to develop

**Pull request closed without merging**
