### PR TITLE
Added tracing support

### LINKED ISSUE #3506: Create module to integrate google trace
## What is the motivation for adding / enhancing this feature?

https://cloud.google.com/trace/docs/setup/nodejs

It will help a lot to improve the latency. We should have the   

```
projectId: 'your-project-id',
  keyFilename: '/path/to/key.json'
```

provided from the config file, module should be placed in `src` (not a core module)

### PR DESCRIPTION
**Pull request by ResuBaka**
### Related issues

closes #3506 

### Short description and why it's useful

This adds support to load a tracing library at the start of the app.

I have added an example for google cloud tracing.

You would use it like this.
src/trace/index.js

```javascript

module.exports.default = () => {
require('./googleCloud')
}

```
 

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [X] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by pkarw** [comment]
@ResuBaka could you please check the failing CI?

**Comment by ResuBaka** [comment]
It looks like not a problem from my changes.

image
https://travis-ci.org/DivanteLtd/vue-storefront/builds/582552893?utm_source=github_status&utm_medium=notification

Should I still fix it or should some one else fix it?

**Comment by pkarw** [comment]
I belive the problem is that modules can’t extend server.js @filrak this is pretty interesting case

Maybe we can just add a hook in core/server.js that can be bound from within the module just before first request is being handled?

**Comment by pkarw** [comment]
If not extending the modules for server app extensions then this way @ResuBaka proposed is the only way; the only thing is that’s gerrnarijg dependency from core to src but at this stage we do have these dependencies anyway so it’s fine with me

**Comment by pkarw** [comment]
Another idea is to add traces from the src/extensions - https://github.com/DivanteLtd/vue-storefront/blob/master/src/extensions/index.ts which won’t require us to modify core/server; these extensions are being registered only serverside

**Comment by ResuBaka** [comment]
I fist had that Idea too but all tracing stuff should happen as early as it gets. So they trace every thing the right way. 

So with my implementation you can add all tracing frameworks which can be implemented this way be called directly before all other code gets loaded.

**Comment by patzick** [comment]
@ResuBaka so let's wait for #3518 to be finished and then let's make first server module with your change, how does it sound for you? :)

**Comment by ResuBaka** [comment]
I would use the server module but mine needs to be done before express is started/created so it would still be the best to have it like I have done. 

Here you have some info. All of them are telling the user to start it as the first module.
https://docs.datadoghq.com/tracing/setup/nodejs/
image
https://www.elastic.co/guide/en/apm/agent/nodejs/current/express.html
image
https://www.npmjs.com/package/@google-cloud/trace-agent
image

**Comment by filrak** [comment]
@ResuBaka interesting case, turn out we need to have multiple extension points on server

**Comment by pkarw** [comment]
@filrak so please just sync with @ResuBaka and let's have this ready to merge this week

**Comment by pkarw** [comment]
@ResuBaka @filrak - how about this one? Are we merging it in?

**Comment by ResuBaka** [comment]
I would say yes when we don't need typescript support for it or is that done in an other PR? @pkarw

**Comment by pkarw** [comment]
OK, I've merged it in

**Comment by filrak** [comment]
@pkarw 
image ;(

**Pull request merged**
