### PR TITLE
Set cache tag when loading a category

### PR DESCRIPTION
**Pull request by haelbichalex**
### Short Description and Why It's Useful

In the new `catalog-next` module, the cache tag for categories was not set anymore.

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by andrzejewsky** [comment]
@haelbichalex could you also add the change @pkarw requested? once it's done we can merge this.

**Comment by haelbichalex** [comment]
@pkarw Not sure if I understood you correctly. Please check the diff in `core/data-resolver/CategoryService.ts`.

**Comment by haelbichalex** [comment]
@pkarw I moved the feature to `catalog-next/store/category/actions.ts`, but only to `loadCategories`, because I didn't find an occurrence of `findCategories` used in the project. Should it be there as well?

**Comment by andrzejewsky** [comment]
I think it's ready to merge.

**Pull request merged**
