### PR TITLE
Add login and register e2e tests

### PR DESCRIPTION
**Pull request by Aekal**
#1274

### CODE REVIEW

**Comment by pkarw** [comment]
@Aekal i belive this test will fail the second time You run it (email in use) :)

**Comment by pkarw** [comment]
it should rather test some validation (to show, not show error) and to not modify the magento2 data (by registering account); please remember that tests should be executed before any PR

**Comment by Aekal** [comment]
I'm checking only validation, if errors won't show up test will succeed - it works each time I run it ;) But you're right, it shoudl't pass any additional data to magento, so I'll remove form submits

**Comment by pkarw** [comment]
OK, lets just not create the real account

**Comment by Aekal** [comment]
I disabled form submits, so data won't be send. Also added additional validations on focusing out input - now validation will work similar to e.g PersonalDetails in Checkout

**Pull request merged**
