### PR TITLE
Process (scoped) packages prefixed with vsf- through webpack

### LINKED ISSUE #2271: Add packages with prefix vsf- to webpack process
## What is the motivation for adding / enhancing this feature?

Currently none of the third party libs are processed through loaders in our webpack process. While it's ok for most of them it's not ok for 3rd party VS modules. They should he included into our webpack process.

This requires changing regular expressions for loader in `core/build` folder.

## What are the acceptance criteria 

* `node_modules` with name starting from `vsf-` should be included into our webpack process for all loaders (as it would be in in the `core`)

# Can you complete this feature request by yourself?

NO

## Additional information

Feel free to ask for details on slack

### PR DESCRIPTION
**Pull request by zimme**
### Related issues

Fixes #2271, #2395

### Short description and why it's useful

Any package in `node_modules` starting with `vsf-*` or `@<scope>/vsf-` will be processed by webpack

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by pkarw** [comment]
Thanks! Please just update the Changelog please + add a note to the docs (/docs)

**Comment by zimme** [comment]
Changelog and docs updates done

**Comment by zimme** [comment]
⚠️ This PR isn't ready for merge, problems has been reported and I'll look into it next week.

Probably tsconfig that needs changes.

**Comment by filrak** [comment]
Thanks, this is awesome feature!

**Comment by pkarw** [comment]
@kkdg I belive we should add a note to the docs somewhere about the convention of having the `vsf-` prefixed modules transpiled by default

**Comment by zimme** [comment]
Did you guys fix the problem with the tsconfig file that I wrote about?

**Pull request merged**
