### PR TITLE
Event bus import removal

### PR DESCRIPTION
**Pull request by szafran89**
IMO we can remove `EventBus` import and use `$bus` plugin

### CODE REVIEW

**Comment by patzick** [comment]
@szafran89 there should be one consistent way of calling EventBus in components, your proposal is okay to me - would you consider changing all uses with this PR? :)

**Comment by filrak** [comment]
Agree, can you check the other imports too?

**Comment by szafran89** [comment]
Yes, I'll check it tomorrow

**Comment by filrak** [comment]
image

**Comment by szafran89** [comment]
Sorry for delay, I'll check it ASAP :D

**Comment by szafran89** [comment]
@patzick please check again, now should be ready to merge ;) There are a few more places with `EventBus` but can't change it b/c it is called before initiating the component.

**Pull request merged**
