### PR TITLE
chore: Remove every call to the global variable (part 2)

### PR DESCRIPTION
**Pull request by DavidRouyer**
### Related issues

Issue #1540 
Continuation of #1613 
Streamined bodybuilder version & fixed bodybuilder types

### Screenshot of passed e2e tests (if you are using our standard setup as a backend)

(run `yarn tests:e2e` and paste the results. If you are not using our standard backend setup or demo.vuestorefront.io you can ommit this step) 

### Contribution and curently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and [refactoring plan for them](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/refactoring-to-modules.md)

### CODE REVIEW

**Comment by DavidRouyer** [comment]
I'd prefer people to use the rootState and get used to it, and the store is only used to read the state, but I can change it if you want!

**Comment by pkarw** [comment]
@DavidRouyer I don't like such a long statements (i mean `rootStore.state.config.<section>.<property>`)

Please change it if You could and let me know when it's ready to be merged in?

**Comment by DavidRouyer** [comment]
Hm, I can't do that because I'm passing it by value and not by reference :/

**Comment by DavidRouyer** [comment]
I've made a lot of clean up, now the config is loaded once in app.ts. I can't use the `const config = rootStore.state.config` after the imports because the object is passed by value, and the initial state of the config is `{}`. You can use it inside the functions, but at this point it's just 💄. Please merge and change it case by case if you want to.

**Pull request merged**
