### PR TITLE
Add multiple bundle products in the cart

### LINKED ISSUE #2994: Product configurable options - can’t add the same SKU with different configurations to the cart
## Current behavior

When adding a product to cart 2 or more times, each time with different custom options which normally have different prices, the calculated total price is wrong.

## Expected behavior

Тhe total price should be the sum of the prices for each product/options pair added to cart. Instead the price ends up being the quantity multiplied by the price of the last added to cart product (with its options), dismissing the prices of previously added products/options.

## Steps to reproduce the issue

1. Go to: https://demo.vuestorefront.io/gear/gear-3/sprite-yoga-companion-kit-45.html
2. Add the product to cart with default options - price is $75.03.
3. Add the product to cart again but choose "Sprite Stasis Ball 65 cm" option - with the custom option price becomes $79.95.
Check microcart - it shows 2 pieces of the same product with total price $159.90, while expected price is $75.03 +  $79.95 = $154.98.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [X] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome Version 74.0.3729.169 (Official Build) (64-bit)
- OS: macOS Mojave 10.14.5
- Node: 
- Code Version:

### PR DESCRIPTION
**Pull request by andrzejewsky**
### Related issues
closes #2994

### Short description and why it's useful
It adds a possibility to add many bundle products with different configuration to the cart

### Screenshots of visual changes before/after (if there are any)
Screenshot 2019-07-20 at 21 43 14

### Which environment this relates to
- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [x] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

### Contribution and currently important rules acceptance
- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by pkarw** [comment]
@andrzejewsky ok, so after the QA is this one ready to be merged in?

**Comment by andrzejewsky** [comment]
@pkarw exactly + code review

**Comment by pkarw** [comment]
unit tests sounds cool - we can add them waiting for QA response @andrzejewsky wdyt?

**Comment by andrzejewsky** [comment]
@pkarw yeah, sure. I'll add them soon

**Comment by andrzejewsky** [comment]
@pkarw @patzick and tests have been arrived 🚀

**Comment by pkarw** [comment]
So much goodness in the 1.11 ♥️

**Pull request merged**
