### PR TITLE
Backport bugfixes for 1.10

### PR DESCRIPTION
**Pull request by andrzejewsky**
Related prs #3661 #3617 #3604 #3605 #3653 #3629 #3638 #3409 #3593 #3233

### CODE REVIEW

**Comment by gibkigonzo** [comment]
also added backport for #3552, #3551, #3289, #3223, #3548, #3516 (it was related to #3548)

**Comment by andrzejewsky** [comment]
Short info for QA team:
#3661 - checkout, checkbox "Use my company's address details" should work fine
#3617 - untestable from the UI, but please try switch between stores (de/it)
#3604 - check the language switcher
#3605 - test `bundleAllStoreviewLanguages` in config file, when it's enabled the VSF wait's for translations
#3653 - test browser back / forward (eg. category <-> product page)
#3629 - untestable from the UI, (the API would have to return numerical `sku`)
#3638 - enable CS tax calculation and check if the prices are ok
#3409 - just small alignment, cosmetic - add something with discount to the whishlist
#3593 - basically untestable from UI, but for some cases it's possible (look into issue)
#3233 - change quantity in the cart - request should be triggered with small delay
#3552 - look at the screenshots in the issue - there you can catch the difference
#3551 - described in the issue
#3223 - requires to have local API, then you have to disable Elasticsearch and see if VSF can handle errors
#3515, #3516 - scenario in the task

**Comment by alinadivante** [comment]
I verified 3661, 3617, 3233, 3604. @ArturDivante please check the rest of the issues :)

**Comment by ArturDivante** [comment]
Status update:

**Comment by alinadivante** [comment]
@andrzejewsky #3223 #3638 -  untested (no API locally)

**Pull request merged**
