### PR TITLE
[WIP] Feature/vuepress docs

### PR DESCRIPTION
**Pull request by NataliaTepluhina**
### Short description and why it's useful

All Vue-Storefront docs reviewed and moved to Vuepress platform. To check the current view of docs, run `vuepress dev docs` or `npm run docs:dev`

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and [refactoring plan for them](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/refactoring-to-modules.md)

### CODE REVIEW

**Comment by filrak** [comment]
One thing - can this vuepress instance be a separate package in monorepo so we don't need to have vuepress dependency in our main package.json?

**Comment by pkarw** [comment]
@NataliaTepluhina can You please add this new config option to the docs - https://github.com/DivanteLtd/vue-storefront/pull/1764 ?

**Comment by NataliaTepluhina** [comment]
> @NataliaTepluhina can You please add this new config option to the docs - #1764 ?
Added to docs.
@pkarw could you please also provide a short description for "multisiteCommonCart"?

**Comment by pkarw** [comment]
I'm merging this in for 1.4 - please create new PR with further works

**Pull request merged**
