### PR TITLE
Add config option for eager load

### PR DESCRIPTION
**Pull request by dz3n**
### Related issues
https://github.com/DivanteLtd/vue-storefront/issues/3493
### Short description and why it's useful
This pull request will add a config option which could be used to directly load images for product listing instead of showing placeholder. Also markup is updated so placehodler will no longer appear for eagerly loaded images and also the markup for it will dissapear after the image is loaded, even if it is not covered by the eager load prop.
### Screenshots of visual changes before/after
Markup before:
https://www.dropbox.com/s/jl04iona7ht5g1f/Screenshot%202019-09-05%2014.23.58.png?dl=0
Markup after:
Screenshot at 2019-10-10 16-47-29

### Which environment this relates to
- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from develop branch and want to merge it back to develop
- [x] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from release branch and want to merge it back to release
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from hotfix or master branch and want to merge it back to hotfix
### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature
### Contribution and currently important rules acceptance
- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by andrzejewsky** [comment]
@alinadivante / @ArturDivante Please have look at this. Now you should see first 5 images on homepage immediately without palceholders (please test 3G connection as well)

**Comment by ArturDivante** [comment]
Here's how it looks for now:
1st 5 pictures indeed acts diffrently and dont have prior placeholders. However, they are not loaded any faster, and appear exactly the same moment as the rest of them. Behavior on category page is identical. 
Load001

**Comment by dz3n** [comment]
My suggestion is get first images independent of last ones. For example we can call **fetchNewCollection** twice, once outside Promise.all and once inside with **start:** param
Same approach can be implemented on other places like category page


https://github.com/DivanteLtd/vue-storefront/blob/024e040a67fe7baf512bff2b12e3966603446b9c/src/themes/default/pages/Home.vue#L113

**Comment by pkarw** [comment]
@andrzejewsky please decide which option is best one (as for me the 4th one)

**Comment by andrzejewsky** [comment]
for me also option no. 4 sounds reasonable, but @dz3n feel free to push your solution here 👍

**Comment by andrzejewsky** [comment]
as we discussed together with @dz3n - I'm closing it, thanks for you effort and research on it 👍

**Pull request closed without merging**
