### PR TITLE
Feature/add usergroupid for product tax calculation

### PR DESCRIPTION
**Pull request by ResuBaka**
I have updated the `calculateProductTax` to get the new feature to work. 
This does only work when you set the **tax.userGroupId** to a number and have **sourcePriceIncludesTax** and **calculateServerSide** set to `false`. 

### Short description and why it's useful
This is adds tax calculation with **product_tax_class_ids** and **customer_tax_class_ids**.
We had the problem that when only the **product_tax_class_ids** we get the wrong taxes on a product to so we need to use both **product_tax_class_ids** and **customer_tax_class_ids** to get the right **tax class** for a product.

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by pkarw** [comment]
Cool; but two more things:
- we should take the user group from currently logged-in user - how to get it? https://github.com/DivanteLtd/vue-storefront/blob/c17c4ef7f59117692dea5d1649c8f399f6d9c3ce/core/lib/search.ts#L52
- we should apply this logic to `vue-storefront-api` to the `taxcalc.js` helper. The groupId in the API needs to be taken out from the request parameter - reference https://github.com/DivanteLtd/vue-storefront-api/blob/d1532f7eeac229da9e00733d0c9bc7f307fdbc12/src/api/catalog.js#L78

**Comment by ResuBaka** [comment]
Did something change in vue-storefront because when I use my local Installation 1.9.0-rc2  then `$vm0.$store.state.user.current.group_id` is set but `$vm0.$store.state.user.groupId` is null. 
Is that maybe something which is not set because we use magento1? @pkarw 

For the api I would make an Issue for or i need to see how much time I have to work on it.

Then what do you mean by **dynamic groupId**?

**Comment by pkarw** [comment]
To be poerfectly honest with you - I'm not sure how this is being set :) @mdanilowicz was in charge of tier prices few months ago and add this dynamic groups mechanism by this change. But youre' right the group_id property should be on user as well so we could use it - but please just make sure it's the same with m2 and m1 as well

**Comment by ResuBaka** [comment]
I just found out to things first `$vm0.$store.state.user.groupId` is only set with the `user.current.group_id` when `usePriceTiers` is set to true and magento1 and magento2 has both `user.current.group_id` set.

The second one is that we need to redo all our tax calculation when a user login and his groupId is different from the one that is in the config.

**Comment by ResuBaka** [comment]
I need to change the code of PriceTiers a bit as ai need to use the user groupId/groupToken as well and not only PriceTiers alone. 

So we need to test that too after I am finished with the implementation.

**Comment by ResuBaka** [comment]
The PR for adding this also to the API can be found [here](https://github.com/DivanteLtd/vue-storefront-api/pull/307).

**Comment by patzick** [comment]
Thanks @ResuBaka !

**Pull request merged**
