### PR TITLE
Feature/update backwards compatible dependencies

### LINKED ISSUE #4126: Upgrade node packages
## What is the motivation for adding / enhancing this feature?
Running `yarn audit`  on clean installation of vue-storefront on branch master outputs 12110 vulnerabilities. 12101 with high severity. 
Running `yarn outdated` states most of the packages current version being behind wanted semver version and way behind latest versions, thus do not apply minor or major updates.

## What are the acceptance criteria 
- [ ] `yarn audit` shows 0 vulnerabilities
- [ ] `yarn outdated` shows packages apply latest version

## Can you complete this feature request by yourself?
- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information
Screenshot from 2020-02-26 14-50-34

### PR DESCRIPTION
**Pull request by simonmaass**
### Related Issues

closes #4126

### Short Description and Why It's Useful

This only updates the backwards compatible dependencies - all tested and still working

I will updated "Major Update backward-incompatible updates" in seperate PR

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [x] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by simonmaass** [comment]
locally yarn build works...

**Comment by gibkigonzo** [comment]
@simonmaass please change base to `hotfix/v1.11.2`

**Comment by simonmaass** [comment]
@gibkigonzo done

**Comment by simonmaass** [comment]
@gibkigonzo done

**Pull request merged**
