### PR TITLE
WIP: Feature/#1908

### PR DESCRIPTION
**Pull request by jablpiotrek**
### Related issues

https://github.com/DivanteLtd/vue-storefront/issues/1908

### Short description and why it's useful

I've created and registered GA module instead of extension that was implemented already

### Screenshots of visual changes before/after (if there are any)

No UI changes has been introduced.

### Screenshot of passed e2e tests (if you are using our standard setup as a backend)

(run `yarn test:e2e` and paste the results. If you are not using our standard backend setup or demo.vuestorefront.io you can ommit this step) 

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

### Contribution and currently important rules acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [ ] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [ ] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by filrak** [comment]
Thanks! can you solve build errors?

**Comment by jablpiotrek** [comment]
@filrak Filip sorry for the delay with this, I didn't have time to tackle it once again. I will have another try during oncoming weekend and then close it no matter if I succeed or fail.

**Comment by filrak** [comment]
Take your time, it can wait ;) You'll just need to pull the recent changes and adjust every time you go back to this PR

**Comment by jablpiotrek** [comment]
OK, so let me keep this still open for a while :)

**Pull request closed without merging**
