### PR TITLE
#2560 - Redirect to the checkout after adding the items to the cart.

### PR DESCRIPTION
**Pull request by MikeSheward**
### Related issues
#2560

### Short description and why it's useful
After adding items to your cart, redirect to the checkout.

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by pkarw** [comment]
@MikeSheward could You please just update the Changelog (also with the #2706 pleasse)?

**Comment by MikeSheward** [comment]
> @MikeSheward could You please just update the Changelog (also with the #2706 pleasse)?

Ah of course, what version shall i add it to? [1.10.0-rc.1] ? Thanks, i'll update for both.

**Comment by pkarw** [comment]
Yes, 1.10-rc1 or Unreleased is fine @MikeSheward

**Comment by MikeSheward** [comment]
I've updated the changelog for this one,

Thanks

**Comment by pkarw** [comment]
@patzick You can merge this one - it's fine :D To 1.10.rc-1

**Comment by patzick** [comment]
Thanks @MikeSheward and sorry for the delay, i couldn't merged that in so created second PR #2937

**Pull request closed without merging**
