### PR TITLE
Fixed cart sync anomaly

### PR DESCRIPTION
**Pull request by chygoz2**
### Related issues

https://github.com/DivanteLtd/vue-storefront/issues/2639

### Short description and why it's useful

Disabled the **Add to Cart** button when clicked until the product has actually been added to the server cart.

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by chygoz2** [comment]
> Thanks! I belive that debounce() should be implemented in the UI (*.vue) components - not in the Vuex action

So i was thinking that if the debounce were to be implemented in the UI, the user experience might not be the best in the sense that when the add to cart button is clicked, the user will not receive any form of feedback until the duration passed to the debounce function has elapsed. This would tend to make the user click the add to cart button more times than actually intended.

**Comment by pkarw** [comment]
You're right in this situation maybe we need to refactor it a little bit deeper - meaning to move the notification outside of Vuex as well; @patzick what's your opinion on that?

**Comment by patzick** [comment]
@pkarw @chygoz2 
I think the flow should goes this way:
1. `cart/addItem` action returns a promise which is resolved after product is added to cart
2. button awaits for this action and till then its state is 'disabled' so there is no possibility to click again

in this case state of "processing" is kept in button. But we can also can have situation, where we have multiple 'add to cart' buttons, so this also should be covered. So in my opinion best way is to have "adding_to_cart" boolean value in cart store state, which is used by getter like `isAddingToCartInProgress` which is passed to addToCart buttons. So:

- when action is called it sets `adding_to_cart` flag to `true`, buttons are disabled then (or even better - they have some processing state on that behavior to show progress); and after adding to cart (or in case of any error) flag is set back to false.

There is no need to use debounce for that and user is perfectly aware of what is going on.

**Comment by chygoz2** [comment]
@patzick This makes perfect sense. I'll make the necessary changes and update the PR. Thanks!

**Comment by pkarw** [comment]
The isAddingToCart flag shouldn’t be global as it can cause fatal errors (no possibility to add any other product if the request wasn’t successfully fulfilled). I belive it would be far better to use the isProductDisabled flag for this purpose as it uses the product.errors collection which is always set for the specific product only

**Comment by pkarw** [comment]
Closed due to long inactivity. Will be fixed in #2887

**Pull request closed without merging**
