### PR TITLE
Next: Support Windows paths in addition to unix paths for vsf theme module.

### PR DESCRIPTION
**Pull request by carlokok**
### Short Description and Why It's Useful

Current VSF-Next has some unix specific path logic. This fixes that and makes it work on Windows.

### Which Environment This Relates To

- [x] Next 

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)

Note: there's no changelog in Next yet. But this fixes Windows support.

### Contribution and Currently Important Rules Acceptance
- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by andrzejewsky** [comment]
@carlokok wow, thanks! I need to test that - I know we've we had some issues on windows  recently so this one might be helpful

**Comment by carlokok** [comment]
Seems there was another bit left: this fixes theme overrides for components/pages.

**Comment by lukeromanowicz** [comment]
@mdanilowicz could you, please, test it out? :)

**Comment by filrak** [comment]
@mdanilowicz ?

**Pull request merged**
