### PR TITLE
Fix for #3151, #3089 and #3178

### LINKED ISSUE #3151: User token is not refreshed with autoRefreshTokens when invalidated by Magento backend
## Current behavior

When user token is invalidated  by Magento backend, refresh logic is not working in /core/lib/sync/task.ts

The error returned by Magento is: 
{"code":500,"result":"The consumer isn't authorized to access self."}

The check if token is invalidated looks like:
resultString.indexOf('not authorized')) >= 0

So now it is not passed as 'not authorized' !== ' isn't authorized'

## Expected behavior

If user token is invalid and autoRefreshTokens === true, user token should be refreshed 

## Steps to reproduce the issue

1) Create user account
2) Wait timeout to user token invalidated on Magento Backend
3) Reload application home page

## Can you handle fixing this bug by yourself?

- [+] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ +] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser:  Chrome Version 75.0.3770.100
- OS:  MacOS 10.13.6
- Node:  11.3.0
- Code Version:  master

### PR DESCRIPTION
**Pull request by pkarw**
### Related issues

closes #3151, #3178, #3089

Related to: https://github.com/DivanteLtd/vue-storefront-api/pull/302

### Short description and why it's useful

I've changed the way the HTTP errors are treated in the API - now we're checking the HTTP status code instead of the message itself

### CODE REVIEW

**Comment by alinadivante** [comment]
@pkarw please give test instructions, what exactly should we check here

**Comment by pkarw** [comment]
VS has a mechanism for auto-refreshing the user tokens when there is a timeout. We can emulate this issue. Please log-in to VS; go to order history; go to home page; open brower dev tools -> Storage -> Local Storage -> find out the `shop/user/current-token` change the value to `invalid-token-blablabla-greetings-from-alina-the-qa-team-:-)` and go back to order history.

In the netowrk tab there should be whole bunch of errors and then some network requests to refrersh the token and in the end id should still work just fine - the `shop/user/current-token` should be replaced with the valid user token from Magento

**Comment by alinadivante** [comment]
@pkarw I tested this PR again on next.storefrontcloud.io (@patzick did deploy here v1.10.0-rc.1 front and api)
Are u sure that your changes have been merged into release1.10?
Because I see two problems:
1. When user registers new account, there is info "You are logged in" but he isn't logged in. 
image

2.  When I change token and open again my account and refresh page- I noticed two different behavior: 
a) There is info "Consumer is not authorized to access self" but he is still logged in. And in dev-console I see `shop/user/current-token` - my own token ( it wasn't replaced)
image

b)  "Consumer is not authorized to access self" occurs and user is logged out.  `shop/user/current-token` - null
image

**Comment by pkarw** [comment]
The question was if the current develop version of vue-storefront-api has been deployed there @patzick? This one: https://github.com/DivanteLtd/vue-storefront-api/pull/302

I also see some console error - @patzick can you please take a look of it? I can't handle it today

**Comment by patzick** [comment]
@pkarw no, on relase is deployed release/v1.10 branch like here; i cannot deploy develop on next
I'll create backported functionality do release branch in api

**Comment by patzick** [comment]
Connected to https://github.com/DivanteLtd/vue-storefront-api/pull/309
deployed and ready for retests

**Pull request merged**
