### PR TITLE
[#8] Add nested categories support

### PR DESCRIPTION
**Pull request by mercs600**
New behavior you can see on video:
https://www.dropbox.com/s/tq9gprjxjhg05t7/nested_categories.mov?dl=0 

PS. We have some problem In categories model, categories with 4 level doesn't have slugs.

### CODE REVIEW

**Comment by pkarw** [comment]
Wow! @mercs600 its extremely cool!
Slugs are assigned within the category vuex store, it seems like the code has some limitation regarding recurrence level. I can take a look at it on

**Comment by hafeez3000** [comment]
I see limitation after 2 levels, need to re-look into the code.  But feature will be super cool after fixing the issue.

**Comment by pkarw** [comment]
Ok, we need the recurrency in here https://github.com/DivanteLtd/vue-storefront/blob/4beccafd98b072ba1ae1b697f6074866de24c75e/src/store/modules/category.js#L149 :)

**Comment by hafeez3000** [comment]
@pkarw: That is correct and now no issues with slug and no problem with nested category navigation

**Pull request merged**
