### PR TITLE
Eslint support #1477

### LINKED ISSUE #1477: Enforce coding guidelines with ESLint + TSLint + Prettier
https://prettier.io/ is a pretty popular code formatter and it's integrated with a lot of tools.

### PR DESCRIPTION
**Pull request by ResuBaka**
### Related issues
#1477 #2522 

### Short description and why it's useful
This adds eslint for typescript. 
This help to have a more uniform formatting for all JavaScript,Typescript and Vue Files. 

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle]

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### Some more infos

What still needs or should be done is on the eslint rules.  
Here i have tried to have the eslint rules so that there is not formatting changes needed. But here can maybe made some improvements. 
@pkarw @filrak @patzick 

I know that i should add a changelog but that i am going to add when it es ready to merge and the eslint and prettier rules are set on. 

### About the broken test
These i am going to fix when i know which rules we want to have in the eslint rules. When the current erros are okay from the rules i can fix them now. But here i want to wait until i know which rules we want to have.

### CODE REVIEW

**Comment by ResuBaka** [comment]
Here is the code when semi is set to true
```typescript
    const wrapper = mountMixinWithStore(MicrocartProduct, storeMock, {
      propsData: { product }
    });

    (<any>wrapper.vm).removeFromCart();
```

**Comment by pkarw** [comment]
@ResuBaka please take care of the failing CI checks: https://travis-ci.org/DivanteLtd/vue-storefront/builds/526795740?utm_source=github_status&utm_medium=notification

**Comment by ResuBaka** [comment]
I have now fixed most of them. 

I needed to update   "@typescript-eslint/eslint-plugin": "^1.7.1-alpha.17",     "@typescript-eslint/parser": "^1.7.1-alpha.17" both to a alpha stage which has fixed a problem with semicolons. 

Then i have updated the eslint vue package. 

It would be grade to get some feedback on the still open erros on how some of them should be handelt?
Should they be fixed or should the rule be changed around them.

**Comment by ResuBaka** [comment]
For the v-for with an v-if error this can be fixed with: 
1. https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/no-use-v-if-with-v-for.md#allowusingiterationvar-true 
```
"allowUsingIterationVar": true
```
2.  Change the loop into a template element. This i would need to test but i thing this would work. 
```
<template v-for="(segment, index) in totals"> 
        <div
          :key="index"
          class="row pt15 pb20 pl30 pr55 "
          v-if="segment.code !== 'grand_total'"
        >
```

**Comment by ResuBaka** [comment]
I have removed the prettier comments from the PR as for now it only adds eslint typescript support.

**Comment by ResuBaka** [comment]
To summ all up. 

* Now all typescript files are linted with eslint. 
* Most new rules that would be errors are for now set to warning to see if these should be changed back to errors or disabled. 
* Then there are some cases where it can behave not 100% right as the eslint typescript is not as fare as tslint but they work hard on it. 
  *  For now i only found one case. Which is a problem with not-dev rule, that has problems with interfaces and issue for it can be found [here](https://github.com/typescript-eslint/typescript-eslint/issues/342).

**Comment by lukeromanowicz** [comment]
This looks really awesome. The typescript rules look pretty the same as javascript we've been using. Thanks a lot for your hard work!

**Comment by patzick** [comment]
@ResuBaka yarn problem is not related to this issue, i'll test rest when get back my env to working state :)

please for now only update changelog.md

**Comment by ResuBaka** [comment]
Added the linting of typescript files to the changelog.

**Comment by patzick** [comment]
@ResuBaka this yarn problem appears only when i switch to this branch, when im back on develop then it still keeps problem with node-sass in cache but after a while yarn command passes. That's why i thought that problem is with my local environment. Could you check why is this happening?

**Comment by ResuBaka** [comment]
I can check it later on my windows 10 machine. 

On my Linux machine node 10.15.3 and yarn 1.16.0 i don't have that problem with and clean git clone and checkout. 

When you can tell me your version i will try it later on my Windows 10 setup and see if i get the same problem. @patzick

**Comment by ResuBaka** [comment]
@patzick I have just test it on my windows 10 machine. 
Node: 11.5.0
Yarn: 1.12.3

With that setup i have no problem running it.  
We could test it in an travis-ci Windows setup and see if it is there, too. As it does not happen for me. 

Maybe @pkarw  or @filrak  can test it and check if someone of them has the same problem. 

But for me it looks more like you should try to update node or yarn to a newer version and check if that fixes it. Than an issue with my changes itself.

**Comment by pkarw** [comment]
Hi folks, is it ready to be merged in? @patzick

**Comment by pkarw** [comment]
Please make sure that this PR won't revert the: https://github.com/DivanteLtd/vue-storefront/pull/2899

The `rootStore.state.config` is currently deprecated

**Comment by ResuBaka** [comment]
I have accepted all remote changes. So it should not have reverted anything from #2899.

**Comment by ResuBaka** [comment]
I have now fixed the new linting issues. 

But there where some strange merge errors (broken typescript code) after i had merged developer. So maybe this should be tested a bit more that nothing is broken now. 

Then is it normal that when i run the tests that i see this:
image
@pkarw.

**Comment by patzick** [comment]
i've merged developp, improved some linting error and i'm merging it
thanks @ResuBaka for this great work!

**Comment by pkarw** [comment]
Hi! I belive I found some issues regarding this feature - @lukeromanowicz @ResuBaka @patzick 

1. `yarn eslint` which is used by Travis - gets me different errors than `yarn build` and `yarn dev`. For instance with `yarn eslint` I see errors like: https://www.dropbox.com/s/sx6lbscba62nwy0/Screenshot%202019-06-01%2007.25.27.png?dl=0. With the `yarn build` i've got just the warnings (no errors) which causes CI to fail. We do have some misalligment in here.

2. The same screen (https://www.dropbox.com/s/sx6lbscba62nwy0/Screenshot%202019-06-01%2007.25.27.png?dl=0) -> it's very hard to get the real issues when 99% of the lines are warnings. We should adjust the linting rules to the real/current code situation. I mean - we probably should skip some checks like unused vars which generates most of the warnings and fix the rest

**Comment by ResuBaka** [comment]
For the second problem we can add a script like `lint:full` and have the current lint default to `eslint --quiet`. But that is not a good solution and most warnings should be fixed or later changed to errors when most or all warnings are fixed as they are return types which should be used when you use typescript. 

That would for now fix the problem so you can see the errors.

For the first one do you have a branch or commit with wich i could test it or see it? @pkarw

**Pull request merged**
