### PR TITLE
#99 product gallery

### PR DESCRIPTION
**Pull request by nuovecode**
I created the array of gallery img in the [product page](https://github.com/bitbull-team/vue-storefront/blob/feature/99-gallery/core/pages/Product.vue) but I think that this job should be done within vue-storefront-api and it should include the whole gallery.

Zoom opens when double clicked because the click event was intercepted by the swipe. If you have better ideas let me know. 

Is SRR support for product image missing?

### CODE REVIEW

**Comment by filrak** [comment]
Thanks! Can you provide screenshots for default theme version?

**Comment by pkarw** [comment]
Could you please @nuovecode add a special case when the returned gallery array is by any reason empty to display the single default image?

**Comment by pkarw** [comment]
There is one more case to handle; after switching the product variant (https://www.dropbox.com/s/2v793yocqo1gcmn/Screenshot%202018-04-02%2017.27.53.png?dl=0) the current (`this.product.image`) product image is switched to the variant-one - which is great because You can display the image of specific variant and check if it's suitable - color, size etc.

We need to have this behaviour. If you need to have the variant's images on the `gallery` list to implement this - no problem, You can just modify https://github.com/bitbull-team/vue-storefront/pull/1/files - change the "else" section to join the configurable_children images to the media_gallery

**Comment by pkarw** [comment]
Another case is offline support. In ofline mode we should have just the pre-cached image displayed in the gallery or even switch off gallery view?

The offline mode image is the one displayed on the product list. You can get by:
```
import { productThumbnailPath } from 'core/helpers'
const offlineImageUrl = productThumbnailPath(this.product, true)
```

So maybe it's an option to get it as the only one gallery item in case of

```
if (typeof navigator !== 'undefined' && !navigator.onLine) {
```

**Pull request closed without merging**
