### PR TITLE
Bugfix/too early breadcrumbs change

### PR DESCRIPTION
**Pull request by filrak**
### Related issues

none

### Short description and why it's useful

Currently when switching from category to Product page breadcrumbs are changing too early.
I fixed this problem by maiing use of internal breadcrumbs in Product page. there are still some side effects to clean (get rid of global breadcrumbs store) and Changelog to be finished.

also depreciation of `@vue-storefront/store` needs to be merged

### CODE REVIEW

**Comment by filrak** [comment]
Even after merge it's still showing already commited changes
Here is the file i changed in this PR https://github.com/DivanteLtd/vue-storefront/pull/2469/files#diff-53623d3d96444676ad00f4011dfaafe2

**Comment by patzick** [comment]
@filrak is it still WIP?

**Comment by filrak** [comment]
nope, just contains  https://github.com/DivanteLtd/vue-storefront/pull/2464 . that needs to be merged first. 2 first files are refering to this PR

**Comment by pkarw** [comment]
The issue hasn't been yet solved by this PR :( It still exists

**Pull request merged**
