### PR TITLE
#2663 fix multiple orders per submit error

### LINKED ISSUE #2663: Errors in checkout stack into multiple orders per submit
## Current behavior
The more times you submit an order with invalid data (i.e. only numbers in the name fields) the more times there will be a submit order request sent to the backend. First submit will send only one request, another submit w/o fixing errors will send the order twice, etc.

## Expected behavior
Order requests having error are being repeated over and over.

## Steps to reproduce the issue
1. try to place an order with invalid user data (i.e. a few digits in name fields)
2. hit submit button several times
3. the more times you hit the button the more requests will be sent to the backend incrementally.

# Can you handle fixing this bug by yourself?

- [x] YES but not anytime soon, feel free to fix it
- [ ] NO

# Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 72
- OS: Ubuntu 18.04
- Node: 8
- Code Version: develop

### PR DESCRIPTION
**Pull request by AndreiBelokopytov**
### Related issues

closes #2663 

### Short description and why it's useful
It prevents repeating order requests by disabling order caching in case of sever error (over than 200 status). Also changed text of notification message.

### Screenshots of visual changes before/after (if there are any)
https://yadi.sk/i/IX8Pw-alt2XI2Q

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [x] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by pkarw** [comment]
Please do test od the order is being queued in Caden if offline mode / no network connectivity.

Please do also check what’s happening with the directOrsers mode is off (so when by default order is being queued); in that case we should probably remove it from the queue in case of wrong HTTP status

Please remember to update the vs-api and to try checking the response codes because as you wrote in the issue: 500 error / like a database error /
Whatever is a different story than Magento2 api error (in this case 99% is a validation issue)

**Comment by pkarw** [comment]
@AndreiBelokopytov how about the proposed changes?

**Comment by AndreiBelokopytov** [comment]
> @AndreiBelokopytov how about the proposed changes?

Hi @pkarw.  I will take a look at it one of these days

**Comment by lukeromanowicz** [comment]
@AndreiBelokopytov if you don't mind I'll fix it myself because we really need it in 1.9 and I'd like to fix the old notification instead of introducing some new code.

**Pull request closed without merging**
