### PR TITLE
Improve e2e tests

### PR DESCRIPTION
**Pull request by Aekal**
#1377 
I'll refactor the remaining tests later

### CODE REVIEW

**Comment by Aekal** [comment]
Mostly done, only product-page test todo (but I can finish it in another PR)

**Comment by Aekal** [comment]
... and done, @pkarw please take a look :)

**Comment by pkarw** [comment]
Thanks Damian! I’m on short Holidays. @alinadivante ciuld you please do a CR of the changes provided by Damian?

**Comment by alinadivante** [comment]
Hi! I also just came back from holidays. @pkarw  I will try to review the code as soon as possible.

**Comment by alinadivante** [comment]
@Aekal nice job! All tests work!
The code looks very good, nice selectors! I'm still learning, so thanks for these improvements and tips :)

**Pull request merged**
