### PR TITLE
Added support to configure custom auth header

### LINKED ISSUE #5078: Add support for custom auth header
We added support to pass token in header instead of query param at [PR](https://github.com/DivanteLtd/vue-storefront/pull/4626 )

In this PR we used Authorization header along with  Bearer scheme, but this will not work if server support other than Authorization header for token authentication. 

Proposal to add tokenHeaderName in config.user property, default value will be "Authorization", if tokenInHeader set to true then getPayload method will use the tokenHeaderName else not.

### PR DESCRIPTION
**Pull request by dixitdeepak**
### Related Issues

closes #5078

### Short Description and Why It's Useful

Added support to configure custom auth header. User can define the auth header name in config file, this will work with tokenInHeader configuration. If tokenInHeader set to true, getPayload will use the tokenHeaderName and send token along with it.

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by Fifciu — CHANGES_REQUESTED** [review]
Amazing job! It looks great. However, I would like to propose another functionality. We should make adding prefix like "Bearer" optional. E.g. let's add new option in config which contains `prefix`. If it is empty - do not add any prefix. Otherwise, add it before token. The default value should be probably just a `Bearer`.

**Comment by dixitdeepak** [comment]
Thanks for review @Fifciu, Let me update code

**Comment by dixitdeepak** [comment]
I'd like to use tokenAuthenticationScheme instead of prefix
https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#Authentication_schemes

**Comment by Fifciu** [comment]
Sound reasonable. But there might be some custom shapes like `AWS4-HMAC-SHA256` which is not a part of the table here (https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml). I would like to support more than less shapes. 

How do you see the implementation?

**Comment by dixitdeepak** [comment]
Updated code, used tokenAuthScheme in default.json config file, default value will be `Bearer`

**Review by Fifciu — APPROVED** [review]
Ok, looks cool thanks

**Comment by dixitdeepak** [comment]
> Sound reasonable. But there might be some custom shapes like `AWS4-HMAC-SHA256` which is not a part of the table here (https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml). I would like to support more than less shapes.
> 
> How do you see the implementation?

Frankly speaking, I haven't got a chance to work with custom shapes.
General pattern for Authorization header is like

`Authorization: <type> <credentials>`

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization

So I think we can use any type with the current implementation, but if we want to prepare customize token then we need to do customization in token preparation work .

**Review by gibkigonzo — APPROVED** [review]

**Pull request merged**
