### PR TITLE
Fix query string dependency

### PR DESCRIPTION
**Pull request by septoctobre**
Can't compile with query-string 6.13.4

```
vsf-app_1   | ERROR in /var/www/core/lib/multistore.ts
vsf-app_1   | ./core/lib/multistore.ts
vsf-app_1   | [tsl] ERROR in /var/www/core/lib/multistore.ts(153,43)
vsf-app_1   |       TS2345: Argument of type '{ [key: string]: unknown; }' is not assignable to parameter of type 'Record<string, string | number | boolean | (string | number | boolean)[]>'.
vsf-app_1   |   Index signatures are incompatible.
vsf-app_1   |     Type 'unknown' is not assignable to type 'string | number | boolean | (string | number | boolean)[]'.
vsf-app_1   |       Type '{}' is missing the following properties from type '(string | number | boolean)[]': length, pop, push, concat, and 26 more.
vsf-app_1   | 
vsf-app_1   | ERROR in /var/www/core/lib/search/adapter/api/searchAdapter.ts
vsf-app_1   | ./core/lib/search/adapter/api/searchAdapter.ts
vsf-app_1   | [tsl] ERROR in /var/www/core/lib/search/adapter/api/searchAdapter.ts(76,45)
vsf-app_1   |       TS2345: Argument of type 'HttpQuery' is not assignable to parameter of type 'Record<string, string | number | boolean | (string | number | boolean)[]>'.
vsf-app_1   |   Index signature is missing in type 'HttpQuery'.
vsf-app_1   | 
vsf-app_1   | ERROR in /var/www/core/lib/search/adapter/api-search-query/searchAdapter.ts
vsf-app_1   | ./core/lib/search/adapter/api-search-query/searchAdapter.ts
vsf-app_1   | [tsl] ERROR in /var/www/core/lib/search/adapter/api-search-query/searchAdapter.ts(84,45)
vsf-app_1   |       TS2345: Argument of type 'HttpQuery' is not assignable to parameter of type 'Record<string, string | number | boolean | (string | number | boolean)[]>'.

```

### CODE REVIEW

**Comment by gibkigonzo** [comment]
@septoctobre please make rebase to `hotfix/v1.12.3` and also run `yarn install`. I think `yarn.lock` should be also changed :thinking:

**Comment by septoctobre** [comment]
@gibkigonzo Done! Let me know if something is missing, thanks.

**Comment by gibkigonzo** [comment]
@septoctobre please do `git rebase @vuestorefront/hotfix/v1.12.3` You can see that in changes there are also changes from master. It would be great to have only your changes :) I think rebase to remote branch hotfix/v1.12.3 should work in that case

**Review by gibkigonzo — APPROVED** [review]

**Comment by gibkigonzo** [comment]
thanks @septoctobre

**Comment by simonmaass** [comment]
wouldnt it be better to fix the type errors?

**Comment by tomymehdi** [comment]
Hello, 

I'm following this tutorial: https://docs.vuestorefront.io/guide/cookbook/setup.html#_2-recipe

No trouble on the vue-storefront-api setup. But when trying to setup the frontend with vue-storefront github project using the tutorial I found this error keep appearing and this merge request that solves it.

The following branches are failing to compile: 
master
v1.12.0
v1.12.1
v1.12.2
Didn't try other branches, just applied myself this code. I recommend creating a new release 1.12.3 with this fix. 

Kind Regards

**Pull request merged**
