### PR TITLE
Easier Contributions

### PR DESCRIPTION
**Pull request by svenefftinge**
Hey there 👋 
We are on a mission to simplify open-source work and encouraging contributors to get started, through automated dev environments.

This PR adds a minimal config to this repo, which allows your community to quickly spin up a ready-to-code dev environment. Please note, that this not only automates the setup of a dev environment but also pre-builds the project before users open it - think CI for dev environments.

I have configured it so, that during prebuild `yarn install && yarn installer` is executed using the default values (i.e. using `https://demo.vuestorefront.io` as api backend). It would be certainly feasible to get all the backend services setup as well.

I also installed a bunch of VS Code extensions that are useful for Vue/TS/Node development.
You can try it out yourself:

https://gitpod.io/#https://github.com/svenefftinge/vue-storefront/tree/develop

If you think this could be useful for your community, I'll be happy to also add your project to https://contribute.dev.

### Screenshots of Visual Changes before/after (if There Are Any)
Screenshot 2020-02-10 at 13 21 35

### Which Environment This Relates To
It doesn't affect a certain deployment, as it is an optional development setup.

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance
- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by andrzejewsky** [comment]
This is awesome! I like the idea! Just one comment here: instead of using an installer, you can call just `yarn install` and `yarn dev` to run the development mode. When it comes to api - it depends: I think it the `next.storefrontclooud.io.` supposed to be there instead, because demo has the newest stable version which means there could be differences between develop and the current stable one. Basically you can use simply use `echo / cat` to create a local config that overrides just this field - something like: `echo "{ api: { url: '....' }}" >> local.json`

**Comment by svenefftinge** [comment]
Cool, thanks for the feedback. Getting rid of the hack I put around the installer is great. 
I've updated the PR.

Btw. I'd suggest you set the 'develop' as the default branch, so GitHub (and Gitpod) will use that for new PRs automatically.

Screenshot 2020-02-12 at 08 31 21

**Comment by svenefftinge** [comment]
FWIW I don't think the failing Travis build is due to my changes.

**Comment by svenefftinge** [comment]
@andrzejewsky should I do anything about the CI build (I cannot manually restart it)?

**Comment by andrzejewsky** [comment]
@svenefftinge ok great! default branch should be master in our repository - but is there any possibility to change that to develop in the gitpod.yml? Actually it can be master as well, but usually `develop` branch is dedicated to new features/improvements. Anyway, from my side, it's ready to merge, just let me know 👍

**Comment by svenefftinge** [comment]
Ok, I think it is good to merge then. Please [reach out](https://community.gitpod.io) in case you have issues with it.

**Pull request merged**
