### PR TITLE
Auto refresh

### PR DESCRIPTION
**Pull request by AurelienLavorel**

### CODE REVIEW

**Comment by filrak** [comment]
I dont think auto refresh is a good idea. It will add traffic without a reason

**Comment by pkarw** [comment]
@filrak this is just the first request when app is being built by web pack and it takes like 90s this is quite usefull for me :)

**Comment by pkarw** [comment]
@AurelienLavorel could you add very basic but proper html markup around the document - html /head / body? Maybe just load some static template from like: /var/app-loaded.html file

**Comment by AurelienLavorel** [comment]
Yes it's just to avoid spamming F5 on that page, here we can make another task, we'll see title update when page is ready.
@pkarw I updated html

**Comment by pkarw** [comment]
Thanks!

**Pull request merged**
