### PR TITLE
Defense against incomplete config in ssr renderer

### PR DESCRIPTION
**Pull request by oskar1233**
### Short description
Adds some defensive config fetching in SSR renderer. Protects against incomplete config, e.g. after update.

Relates to `develop` (test version).

No upgrade steps required.

### CODE REVIEW

**Comment by oskar1233** [comment]
@pkarw It comes down to project's policy - personally I'd wrap every user's (developer's) input like this.

**Comment by andrzejewsky** [comment]
@oskar1233 same here, please create this PR from `release/v1.11`.

**Comment by oskar1233** [comment]
@andrzejewsky Sorted here as well.

**Comment by andrzejewsky** [comment]
@oskar1233 you have errors to fix, look into the build

**Pull request merged**
