### PR TITLE
Feature/disable compare by configuration

### PR DESCRIPTION
**Pull request by bernarddelhez**
### Related Issues
New feature for vsf-default theme: https://github.com/DivanteLtd/vsf-default/pull/22

### Short Description and Why It's Useful
The new configuration 'compare.enabled' allows to disable the compare feature.
It's useful because this feature does not make sense in all kind of shops.

### Screenshots of Visual Changes before/after

compare_before_after

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by gibkigonzo** [comment]
I'm not sure about this. If you don't want to have a compare button, you should remove it :woman_shrugging: The default theme is just the starting point. When we add v-if, the comparison button will not be displayed, but will still be included in the bundle. Which means it won't be completely removed. The best option is to delete it if you don't need it.

**Comment by bernarddelhez** [comment]
@gibkigonzo 
Would you have another solution to deactivate the compare module?
I have the problem with the update ability, because if I remove all entries in the vsf-theme to compare, they would reappear at the next vsf-theme update. Maybe there is another solution here?
Thanks

**Comment by gibkigonzo** [comment]
There is no other option then remove it. Default theme (or Capybara) should be a starting point. If your store is more or less same as those themes then you can relay on updates. But we recommend to copy it and create your own theme based on default.

**Comment by pkarw** [comment]
The compare feature should be remove via commenting out the module allowed in src/modules and then by removing all the theme references. It shouldn’t be adobe via anothe rconfigurabe option. We’re trying to make the core even simpler with each subsequent release and this feature is rather against loose coupling principle. I’d suggest to close this PR @gibkigonzo 

@bernarddelhez thanks for your contribution, I appreciate your time but we can’t accept this feature. We will be more than happy to merge in some feature from you if you’d find time to pick any of the issues marked for the upcoming releases 🙌

**Pull request closed without merging**
