### PR TITLE
General Information updates

### LINKED ISSUE #2758: Adjust Introduction to medium post
https://medium.com/the-vue-storefront-journal/introduction-to-vue-storefront-a-quick-getting-started-guide-d119023ed67d

https://docs.vuestorefront.io/guide/#what-is-vue-storefront

TODO:
- Create "General information" label for docs category
- Adjust the linked doc to medium post

### PR DESCRIPTION
**Pull request by kkdg**
### Related issues

closes #2758 (not complete)

### Short description and why it's useful

filling the link and refining docs

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [x] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by pkarw** [comment]
Is it ready to merge in?

**Comment by kkdg** [comment]
Yes @pkarw , but waiting for a review from @filrak

**Comment by filrak** [comment]
I guess it's better not to duplicate this doc. README should be different than introduction itself. Usually on README you could find things like installation guide etc so maybe we could gather some links on this page that can guide newcomers ?

**Comment by kkdg** [comment]
@filrak A reasoning behind that is historical. README in the root docs had all the info about introduction, that's OK but by newly creating a new section solely intended for introduction made it a duplicate. I thought the best solution for this would be an inclusion of another markdown in a markdown, so that README doesn't have to contain duplicated content except an inclusion syntax, but found no clean solution so far.
How do you want it? Another page for useful links or guidance in README anyhow conflicts with the purpose of the introduction section. By the way, the inclusion doesn't make any difference for users because I changed the link from the gateway ("Get Started button on / ") directed to introduction page directly.

**Comment by kkdg** [comment]
Or if I understood you @filrak correctly, you meant to stuff the entrance(README) with a few big buttons divided by sections such as Installation, Integration, video guide and so on which are first direction guide, e.g. Kubernetes page - [K8s intro](https://kubernetes.io/docs/home/)

**Comment by filrak** [comment]
@kkdg i not to think about this, right now i guess we can merge it in. I'm not sure which approach is better

**Pull request merged**
