### PR TITLE
#96 Icons for remove/edit actions for minicart

### LINKED ISSUE #96: Escape key should hide microcart and sidebar

### PR DESCRIPTION
**Pull request by dimasch**
Fixed #96 Issue

### CODE REVIEW

**Comment by filrak** [comment]
Thank you for your contribution! Before I can merge this pull request please fix issues listed below:

1. The task is not connected with #96 - please edit the description 
2. According to designs in Figma the icons should be labeled

**Comment by dimasch** [comment]
Update pull - icons labeled.

**Comment by filrak** [comment]
Looks good, thank you!

**Pull request merged**
