### PR TITLE
Feature/vuex refactor

### PR DESCRIPTION
**Pull request by pkarw**

### CODE REVIEW

**Comment by filrak** [comment]
@kacperknapik  please resolve the conflicts

**Comment by kacperknapik** [comment]
@filrak done

**Comment by pkarw** [comment]
Who's the brave one to merge this to master? :) @filrak @kacperknapik

**Comment by kacperknapik** [comment]
let me test it one more time @filrak @pkarw

**Comment by kacperknapik** [comment]
missing mutation added, ready to merge

**Comment by pkarw** [comment]
@kacperknapik have you tested the variants? Does everything work like it should?

**Comment by kacperknapik** [comment]
@pkarw variants work correctly imho, no errors show up, I think it is ready to go. you can double check that if you want

**Comment by pkarw** [comment]
OK, I'll merge it for you @kacperknapik

**Pull request merged**
