### PR TITLE
Feature 2184: Payment Request API Integration

### PR DESCRIPTION
**Pull request by qiqqq**
### Related issues

#2184

### Short description and why it's useful

Adds Payment Request API Integration. Payment process is mocked now and payment data are not sended to any payment service provider. Payment is always success and order is processed to Magento.

### Screenshots of visual changes before/after (if there are any)

https://prnt.sc/me8hav

### Screenshot of passed e2e tests (if you are using our standard setup as a backend)

No screenshots

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by dimasch** [comment]
I am check right now compatibility with Paypal module. 
FYI

**Comment by dimasch** [comment]
@filrak I see error in `yarn build` with paypal module:
But this error related to paypal module, and i fixed it.

```
ERROR in ./src/modules/instant-checkout/components/Button.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/modules/instant-checkout/components/Button.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve '@vue-storefront/store/lib/multistore' in '/Users/dima/workspace/vsf-paypal/vue-storefront/src/modules/instant-checkout/components'
 @ ./src/modules/instant-checkout/components/Button.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/modules/instant-checkout/components/Button.vue?vue&type=script&lang=js&) 13:0-72 14:16-32
 @ ./src/modules/instant-checkout/components/Button.vue?vue&type=script&lang=js&
 @ ./src/modules/instant-checkout/components/Button.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/themes/default/components/core/blocks/Microcart/Microcart.vue?vue&type=script&lang=js&
 @ ./src/themes/default/components/core/blocks/Microcart/Microcart.vue?vue&type=script&lang=js&
 @ ./src/themes/default/components/core/blocks/Microcart/Microcart.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/themes/default/layouts/Default.vue?vue&type=script&lang=js&
 @ ./src/themes/default/layouts/Default.vue?vue&type=script&lang=js&
 @ ./src/themes/default/layouts/Default.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/themes/default/App.vue?vue&type=script&lang=js&
 @ ./src/themes/default/App.vue?vue&type=script&lang=js&
 @ ./src/themes/default/App.vue
 @ ./src/themes/default/index.js
 @ ./core/app.ts
 @ ./core/client-entry.ts
 @ multi babel-polyfill ./core/client-entry.ts

ERROR in ./src/modules/paypal/store/actions.ts
Module not found: Error: Can't resolve '@vue-storefront/store/lib/multistore' in '/Users/dima/workspace/vsf-paypal/vue-storefront/src/modules/paypal/store'
 @ ./src/modules/paypal/store/actions.ts 2:0-78 7:45-67 24:45-67
 @ ./src/modules/paypal/store/index.ts
 @ ./src/modules/paypal/index.ts
 @ ./src/modules/index.ts
 @ ./core/modules-entry.ts
 @ ./core/app.ts
 @ ./core/client-entry.ts
 @ multi babel-polyfill ./core/client-entry.ts

ERROR in /Users/dima/workspace/vsf-paypal/vue-storefront/src/modules/paypal/store/actions.ts
```

**Comment by dimasch** [comment]
- `store/lib/multistore` has been moved to `core/lib/multistore` (#2224)

**Comment by filrak** [comment]
@qiqqq what is the status of PR?

**Comment by qiqqq** [comment]
@dimasch I fixed this error

**Pull request merged**
