### PR TITLE
[DOCS] cookbook added 

### LINKED ISSUE #2992: Cookbook
# Summary
[summary]: #summary

Writing a cookbook style guides for Vue Storefront in ./docs folder

# Motivation
[motivation]: #motivation

This helps a lot for new comers to wrap their heads around how to use Vue Storefront to their advantage. 

# Guide-level explanation
[guide-level-explanation]: #guide-level-explanation

It explains the step-by-step guides with respect to how to start Vue Storefront from scratch. 
It deals with common issues frequently faced by new comers. 
1. Data Imports
2. Setup Elastic Search
3. Starting from scratch
4. Integration with 3rd party
5. Extend a module
6. Theming
7. Dealing with common mistakes and pitfalls
8. and so on...

# Reference-level explanation
[reference-level-explanation]: #reference-level-explanation
This guide follows the proven design for general cookbook which is easy to understand, easy to follow the steps and help users to stay on track with clear solution for certain type of problems. 
It contains 4 ~ 5 sections for each recipe (solution), and a handful recipes comprise a chapter. 
Sections include : 
- Preparation
- Recipe
- Peep into the kitchen (how it works internally)
- Chef's secret (protips)

# Drawbacks
[drawbacks]: #drawbacks

It takes a lot of time to build a cookbook that is relevant. 

# Rationale and alternatives
[rationale-and-alternatives]: #rationale-and-alternatives

- Cookbook is generally known as the best way for helping newbies and new comers get started at all. 
-  Tutorial is good for helping new comers too but cookbook has a variety of helps in a more structured way. 

# Unresolved questions
[unresolved-questions]: #unresolved-questions

- You may add/remove topics

# Future possibilities
[future-possibilities]: #future-possibilities

We can build a lot more stuff to help new comers and users who lost in the middle.

### PR DESCRIPTION
**Pull request by kkdg**
### Related issues

closes #2992 partially. 

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [ ] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [ ] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by pkarw** [comment]
@filrak can You please take a look at it?

**Comment by pkarw** [comment]
@kkdg isn’t it already in the master as the cookbooks are published to docs.vuestorefront.io?

**Comment by kkdg** [comment]
@piotr Actually, no. `now` provides a feature to deploy from CLI and alias it. I mean, it's kinda a bypass for the sake of bypass. Hmm, should I not use it?

**Comment by pkarw** [comment]
You mean you did publish from your private fork or kind of branch and we still need to merge it to the master? I mean: for me it's fine I just wanted to make sure if I should merge this PR in or not (it's opened for 23 days so wasn't sure)


Should I merge it? :)

**Comment by kkdg** [comment]
It's fine not to merge PR when it comes to maintaining docs.vuestorefront.io however, considering docs management and history record, I want it to have commits as small chunks as possible to avoid a huge amount of conflicts we may have someday down the road ;)

**Comment by patzick** [comment]
I'm not seeing any reason why not to merge this, especially if this is already deployed, because no one can propose improvements. @kkdg do you see reasons why not to merge this?

**Comment by kkdg** [comment]
@patzick I don't see any reason not to merge either. please merge it.

**Pull request merged**
