### PR TITLE
feat: tree shaking and lazy loading for translations

### PR DESCRIPTION
**Pull request by DavidRouyer**
- **[BREAKING]**: Removed translations() from lib/themes.js
- Only English is bundled in app.js because it's the default language
- The default locale is lazy loaded
- **[DOWNSIDE]**: need to restart Webpack to update translations

before
after

Before:
```
                     Asset      Size  Chunks                    Chunk Names
                runtime.js  1.46 KiB       0  [emitted]         runtime
                    app.js   724 KiB       1  [emitted]  [big]  app
    core-service-worker.js  7.66 KiB       2  [emitted]         core-service-worker
                 vendor.js   542 KiB       3  [emitted]  [big]  vendor
            runtime.js.map  7.75 KiB       0  [emitted]         runtime
                app.js.map  1.84 MiB       1  [emitted]         app
core-service-worker.js.map  1.55 KiB       2  [emitted]         core-service-worker
             vendor.js.map  2.12 MiB       3  [emitted]         vendor
                index.html  1.31 KiB          [emitted]         
```

After:
```
                     Asset      Size  Chunks                    Chunk Names
    lang-ru-RU-json.js.map  95 bytes       0  [emitted]         lang-ru-RU-json
        lang-ru-RU-json.js  16.7 KiB       0  [emitted]         lang-ru-RU-json
        lang-pl-PL-json.js    18 KiB       2  [emitted]         lang-pl-PL-json
        lang-nl-NL-json.js  15.2 KiB       3  [emitted]         lang-nl-NL-json
        lang-jp-JP-json.js  12.3 KiB       4  [emitted]         lang-jp-JP-json
        lang-it-IT-json.js  15.1 KiB       5  [emitted]         lang-it-IT-json
        lang-fr-FR-json.js  18.1 KiB       6  [emitted]         lang-fr-FR-json
        lang-es-ES-json.js  15.3 KiB       7  [emitted]         lang-es-ES-json
        lang-de-DE-json.js  17.5 KiB       8  [emitted]         lang-de-DE-json
                runtime.js  2.37 KiB       9  [emitted]         runtime
                 vendor.js   540 KiB      10  [emitted]  [big]  vendor
    core-service-worker.js  7.66 KiB      11  [emitted]         core-service-worker
                    app.js   581 KiB      12  [emitted]  [big]  app
        lang-pt-BR-json.js    17 KiB       1  [emitted]         lang-pt-BR-json
    lang-pt-BR-json.js.map  95 bytes       1  [emitted]         lang-pt-BR-json
    lang-pl-PL-json.js.map  95 bytes       2  [emitted]         lang-pl-PL-json
    lang-nl-NL-json.js.map  95 bytes       3  [emitted]         lang-nl-NL-json
    lang-jp-JP-json.js.map  95 bytes       4  [emitted]         lang-jp-JP-json
    lang-it-IT-json.js.map  95 bytes       5  [emitted]         lang-it-IT-json
    lang-fr-FR-json.js.map  95 bytes       6  [emitted]         lang-fr-FR-json
    lang-es-ES-json.js.map  95 bytes       7  [emitted]         lang-es-ES-json
    lang-de-DE-json.js.map  95 bytes       8  [emitted]         lang-de-DE-json
            runtime.js.map    12 KiB       9  [emitted]         runtime
             vendor.js.map  2.11 MiB      10  [emitted]         vendor
core-service-worker.js.map  1.58 KiB      11  [emitted]         core-service-worker
                app.js.map  1.66 MiB      12  [emitted]         app
                index.html  1.96 KiB          [emitted]
```
app.js reduced from 724 KiB to 581 KiB

### CODE REVIEW

**Comment by pkarw** [comment]
Seems like a way to go. What does it mean "TODO" - it seems like `loadLanguageAsync` is already used in the PR? The second question is about the checks - some failed, could You check it?

Let me know when I should merge it in

**Comment by DavidRouyer** [comment]
I need to use `loadLanguageAsync` in multistore.js when we switch from one store to another (and then one language to another) to lazy load the language and set it

Yeah, eslint doesn't like the `import()` that I use to lazy load things

**Comment by DavidRouyer** [comment]
The build is passing

**Comment by pkarw** [comment]
Merging in.

**Pull request merged**
