### PR TITLE
Feature/preselect country based on browser language

### PR DESCRIPTION
**Pull request by moezzie**
Adds default country select functionality according to issue: [#312 Add default user's country selection based on browser language](https://github.com/DivanteLtd/vue-storefront/issues/312)

Read the last two characters from navigation.language and preselect country selects in checkout and my account accordingly.

Example:
Users with a German browser would have de-DE as a language. This would select Germany by default.
sv-SE => Sweden
en-UK => United kingdom

##### Checkout Shipping
shipping-after

##### Checkout Shipping (before) (before)
shipping-before

##### Checkout Payments (after)
payment-after

##### Checkout Payments (before)
payment-before

##### My account shipping details (after)
myaccount-shippingdetails-after

##### My account shipping details (before)
myaccount-shippingdetails-before

### CODE REVIEW

**Comment by pkarw** [comment]
Thanks! WIll be merged to R1.2 (as we're releasing 1.1 this week)

**Comment by moezzie** [comment]
@pkarw Yes of corse. I'll add the case of a two character language code and resolve the conflicts in the coming days

**Comment by moezzie** [comment]
* Handling two letter country code fixed
* Conflicts sorted out.

Not sure what is causing the Travis CI errors.

> 11 07 2018 19:43:13.636:ERROR [launcher]: Cannot start Chrome

**Comment by pkarw** [comment]
Thanks! Will merge it next week after holidays :)

**Comment by pkarw** [comment]
@moezzie is this ready to merge? Please take a look at the conficts; after resolving them I'll merge this in!

**Comment by pkarw** [comment]
@moezzie could You please solve the conflict + check this PR once again - I mean please apply your changes to the current master please

**Pull request closed without merging**
