### PR TITLE
We should'nt display cart discounts on product in side cart #1758

### PR DESCRIPTION
**Pull request by mcspronko**
### Related issues

We should'nt display cart discounts on product in side cart #1758

### Short description and why it's useful

The product totals part of the Product.vue template has been removed. Now, minicart shows product prices as is on the line level.

### Screenshots of visual changes before/after (if there are any)

After the fix has been applied:
https://prnt.sc/m8vyst

### Screenshot of passed e2e tests (if you are using our standard setup as a backend)

(run `yarn test:e2e` and paste the results. If you are not using our standard backend setup or demo.vuestorefront.io you can ommit this step) 

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by pkarw** [comment]
Thanks! I believe some of the users might want to display the prices as it was done before - can we add the config.cart.displayItemDiscounts by default (set in default.json) = true for this?

To get the config You can just:

import rootStore from “@vue-storefront/store” and then:

rootStorw.state.config.cart ...

**Comment by mcspronko** [comment]
@pkarw makes sense to add a setting for this, but from a user perspective, seeing total incl tax price on product item level seems like confusing information. What do you think? Maybe we have to just show Price with Incl/Excl Tax on line level?

**Comment by mcspronko** [comment]
@pkarw this is more like "display totals" vs "display product prices" option.

**Comment by pkarw** [comment]
It's fine!

**Pull request merged**
