### PR TITLE
Adding Google Analytics feature #494

### PR DESCRIPTION
**Pull request by hafeez3000**
1) Added https://github.com/MatteoGabriele/vue-analytics in packages.json
2) Defined Google Analytics UA ID to src/config.example.json
3) Initiated Vue-analytics in src/app.js with route option

### CODE REVIEW

**Comment by pkarw** [comment]
@hafeez3000 thanks! Still few things to improve:
- if no google account Id provided, the Vue analytics shouldn’t have been instantiated - let users to decide by setting this option is
- I would propose to add support for this library as a plugin / check the /extensions/mailchimp
- we should support eCommerce events by binding specific event (probably need to be added - event after order is made: order-after-placed) - then bind to such event in your plugin and use https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/ecommerce.md 

The necessity of moving this to the plugin is implied by the assumption of having external services(mailchimp, ga) in plugins, not in the core

Please also check how can we support offline google analytics? This is PWA so we cannot assume that user has internet connection all the time

For reference https://www.npmjs.com/package/sw-offline-google-analytics

https://developers.google.com/web/updates/2016/07/offline-google-analytics

As it says- using this solution you should have out of the box offline support because the mentioned library redo all the requests made to GA automatically 

But please test if it’s fine

Aftter you made the changes mentioned above I’ll be able to merge this feature in

GA is crucial so we have to have it done the right way :)

**Comment by hafeez3000** [comment]
@pkarw: Thank you for your feedback, completely agree with your comments, however this may need sometime to implement.

**Comment by pkarw** [comment]
No worries, please take your time!

**Comment by pkarw** [comment]
Closing this one  because of https://github.com/DivanteLtd/vue-storefront/pull/578

**Pull request closed without merging**
