### PR TITLE
[#1194] Product thumbnail refresh after filter change

### PR DESCRIPTION
**Pull request by mercs600**
fixes issue described in #1194 

@Igloczek check it please

### CODE REVIEW

**Comment by pkarw** [comment]
Its great you fixed it! My fix for that was to use instant flag to disallow lazy loading for first X pictures (it’s in the develop); but would be better to have lazy loading for all objects

**Comment by Igloczek** [comment]
I wrote lots of words in this box, but then found a solution and had to remove everything :D

Now we are using mix of `v-lazy` and `v-lazy-container`, which seems to be redundant and kidna confusing solution.

But we can do it better :)
`v-lazy` [can take object as a value](https://github.com/hilongjw/vue-lazyload#basic), so if we will create `computed` that returns object with all necessary URLs, we can reduce code to this:

```js
imgObj () {
  return {
    src: thumbnail,
    loading: placeholder,
    error: placeholder
  }
}
```

```vue
<div v-if="!instant">
  <img
    :src="placeholder"
    :alt="product.name"
    v-lazy="imgObj"
    height="300"
    width="310"
  >
</div>
```

**Comment by pkarw** [comment]
Seems quite good. Does it work with the filter changes as it's expected?

**Comment by Igloczek** [comment]
I didn't try it.

**Comment by pkarw** [comment]
Could You, please? :D @Igloczek

**Comment by Igloczek** [comment]
RODO vs Free time
500:0

**Comment by pkarw** [comment]
:D OK, I'll test it later then or @mercs600 please do If you could

**Comment by mercs600** [comment]
@Igloczek @pkarw it's done

**Comment by pkarw** [comment]
@mercs600 please just fix the lint error and I'm merging it in:
https://travis-ci.org/DivanteLtd/vue-storefront/jobs/383323726

**Comment by mercs600** [comment]
@pkarw I missed it. It's done. Right now I noticed some other bugs on catalog theme, so I will fix it.

**Pull request merged**
