### PR TITLE
Feature/2637 add to cart wishlist product listing

### LINKED ISSUE #2637: Add to cart from wishlist and add to cart from product listing
## What is the motivation for adding / enhancing this feature?

1. User add items that regularly purchases to a wishlist/favourites. When they want to reorder items from wishlist, they are able to add products directly from the wishlist into the cart without the need to go into each products individual page. This provides a quicker user journey for customers that are regularly purchasing the same items. 
1. Users can go into a category listing. Users can add products to the cart from the product tile without having to go into each individual product page.

## What are the acceptance criteria 

* User can see a quantity and add button for each product in their wishlist.
* When clicking the add button, the desired quantity of that product is added to the cart.
* User can see a quantity and add button under each product tile.
* When clicking the add button, the desired quantity of that product is added to the cart.

# Can you complete this feature request by yourself?

No

## Additional information

The tesco tiles for example:

### PR DESCRIPTION
**Pull request by Hackbard**
### Related issues

closes #2637

### Short description and why it's useful

Added "AddToCart" Button to Wishlist and ProductTile.

### Screenshots of visual changes before/after (if there are any)

Old Version:
Old Version

New Version
New Version

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [X] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [X] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [X] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [X] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by Hackbard** [comment]
> I will block this one for now, considering discussion about this feature; we need to ensure that we can merge that in :)

Yep. Where will that be discussed?

**Comment by patzick** [comment]
@Hackbard i believe #2637  is the best place for that:)

**Comment by pkarw** [comment]
Thanks! We need to polish it a little bit:

a) @alinadivante can You please improve the UX with @StasiekDivante?
b) in case of `configurable` and `grouped product` we need to have the same UI (qty + add to cart) = but clicking Add to cart redirects us the PDP with the qty set + notification (`spawnNotification`) with a message `Please configure the product options`
c) default qty should be = 1
d) when the `product.stock.is_in_stock` == false or `product.stock.qty` == 0 the button should be disabled
e) the wishlist is displayed as a drop down - can You check how it looks like in this mode + paste the screen please?
f) in the #2887 we introduced a fix for adding multiple products to the cart - please do use the same solution:

```
    async addToCart (product: Product) {
      this.isAddingToCart = true
      await this.$store.dispatch('cart/addItem', { productToAdd: product })
      this.isAddingToCart = false
    }
```

**Comment by pkarw** [comment]
@Hackbard hi there! are you still willing to improve this PR and apply the suggested changes in order to merge it in?

**Comment by Hackbard** [comment]
Yes i will do that if we take your suggestions as the new plan

**Comment by pkarw** [comment]
I'm afraid we'll close this one due to long inactivity @Hackbard how do youe see this feature?

**Comment by pkarw** [comment]
Closing due to long inactivity

**Pull request closed without merging**
