### PR TITLE
[update] ux improvement for personnal details step

### PR DESCRIPTION
**Pull request by AurelienLavorel**

### CODE REVIEW

**Comment by pkarw** [comment]
Hi @AurelienLavorel, could you please attach the screen how does it look like after change?

**Comment by AurelienLavorel** [comment]
Of course.

Before:
before
After:
after

I exchange **login** and **next step** position to respect the global design, validation button is always in right position.

When you press "enter" on e-mail field, next step is loaded.

**Comment by pkarw** [comment]
Cool! Such UX improvements are much appreciated! Thanks for that @AurelienLavorel good job.

**Comment by pkarw** [comment]
@AurelienLavorel could you please move the submit buttons related to the other checkout steps to the right as well to make it more coherent? https://www.dropbox.com/s/e2pgvkytc5cgedk/Screenshot%202018-03-18%2012.55.26.png?dl=0

**Pull request merged**
