### PR TITLE
Bugfix/#2863 No placeholders in gallery - offline mode

### PR DESCRIPTION
**Pull request by przspa**
### Related issues
#2863
#2925

### Short description and why it's useful
As wrote @pkarw I changed gallery behavior in offline mode. Now in offline mode we show only offline image without zoom.
I implemented ProductImage to Wishlist, Checkout and Microcart.

### Screenshots of visual changes before/after (if there are any)
offline

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [ ] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by alinadivante** [comment]
@przspa I have placeholders everywhere in offline mode.

**Comment by przspa** [comment]
@alinadivante for me everything is working greate. I only fixed image source for single picture on product page in offline mode.
sw

**Comment by przspa** [comment]
For me this bugfix resolve #2863 and #2925 bug. I tested it and I always have placeholder if image cannot loaded. But I have many cases when I see only placeolder. It's possible that it's a cache problem?

**Comment by pkarw** [comment]
@przspa can You please resolve a conflict with the changelog?

**Comment by przspa** [comment]
@pkarw done

**Comment by pkarw** [comment]
Thanks!

**Pull request merged**
