### PR TITLE
fix: added http status code to cache and caching response

### PR DESCRIPTION
**Pull request by ResuBaka**
### Short Description and Why It's Useful

Currently the http code from a response is not cached and it should as 404 pages can be cached to. The 404 is only an example of status codes that may be cached or are wanted to be cached. 

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [x] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pkarw** [comment]
To be ported into VSF 1.11 as well

**Comment by ResuBaka** [comment]
Do you guys want to add the changelog entry or should I do it?

**Comment by pkarw** [comment]
Yes, please

**Comment by ResuBaka** [comment]
Done @pkarw 

And changed to merge into the hotfix branch. Most of the changes you can see in here are coming from the master as my branch is based on the master.

**Comment by andrzejewsky** [comment]
@ResuBaka I think you have to rebase with the source branch, or cherry-pick your commits

**Comment by ResuBaka** [comment]
I have fixed it :) 

Force push + cherry-pick = :fire:

**Pull request merged**
