### PR TITLE
feature/2811 add buttons to filters view on mobile

### LINKED ISSUE #2811: Add 'Show results' button to filters view on mobile
## What is the motivation for adding / enhancing this feature?

The filters for the list of products in the mobile view are visible in the sliding side tab.
So, the user can not see that by selecting filters the list of products automatically updates.
Switching to filter results by clicking 'x' is not intuitive. 'X' is also not visible when scrolling filters down.
Peek 2019-04-26 11-40

## What are the acceptance criteria 

- [ ] Under the list of filters, the 'Filter' button is visible, which closes the filter sidebar.
- [ ]  "Clear" button is changed according to the prepared design 

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

### PR DESCRIPTION
**Pull request by 965750**
### Related issues
closes #2811 

### Short description and why it's useful
It adds filter button and fixes styles in clear filters 

### Screenshots of visual changes before/after (if there are any)
image

### Which environment this relates to

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by pkarw** [comment]
Please do update the Changelog

**Comment by 965750** [comment]
@pkarw Added

**Comment by 965750** [comment]
320px
image

768px
image

780px
image

1030px
image

1200px
image

**Comment by 965750** [comment]
Teraz trzyma się krańca prawej strony tego containera, chyba że byśmy starali się wyrównać np. z kolorami i rozmiarem, ale trzeba mieć na uwadze, że nie zawsze jest np. tyle kolorów by wypełnić jeden row do końca. Co o tym myślisz @patzick ?

**Comment by pkarw** [comment]
@patzick, @alinadivante I'm really not sure about this change. On the current demo, the "Clear filters" button look & feel is consistent with all the other buttons and Call to Actions (https://www.dropbox.com/s/41xvq33m9ok4fuq/Screenshot%202019-05-29%2010.14.14.png?dl=0).

Why we changed it to kind of label? It doesn't look like clickable element + introduced another vertical span to the design on mobile.

Moreover, I guess the "Filter" button which is non visible on mobile view - should rather stick to the bottom all the time: https://www.dropbox.com/s/uc7ohhnoxnfhukb/Screenshot%202019-05-29%2010.17.12.png?dl=0

@alinadivante can You please create an issue for that and make sure it'll be fixed?

**Comment by alinadivante** [comment]
@pkarw , @965750 will create new PR and it will be fixed

**Pull request merged**
