### PR TITLE
Updating @textarea by @input to check if textarea value is checked

### PR DESCRIPTION
**Pull request by Aylay**
Ref to the issue #1454 

Replace `@textarea="$emit('textarea',` $event.target.value)"`
By `@input="$emit('input', $event.target.value)"`
Change in `src/themes/default/components/core/blocks/Form/BaseTextarea.vue`

### CODE REVIEW

**Comment by pkarw** [comment]
I'm not sur why did You change the 'input' to 'textarea' in here?

**Comment by Aylay** [comment]
@pkarw Ref to the issue #1454

When the textarea field is filled, the textarea label doesn't stay on top of the field.
By changing @textarea in @input, the problem was solved

**Comment by pkarw** [comment]
OK, makes sense

**Comment by pkarw** [comment]
Please fix the es-lint issues before I'll merge it in:
https://travis-ci.org/DivanteLtd/vue-storefront/jobs/407940838

**Comment by Aylay** [comment]
@pkarw I don't understand because I changed one file only : BaseTextarea.vue
How is it possible that there is a problem on another files ?

**Comment by Aylay** [comment]
@pkarw maybe this PR : #1453

**Comment by Aekal** [comment]
@Aylay It looks like your PR is based on develop with eslint error, I fixed it last time. Try to merge latest develop to your branch and it should be fine

**Comment by Aylay** [comment]
ok wait for it :)

**Pull request merged**
