### PR TITLE
Removed: Hardcoded fields in omitSelectedVariantFields.ts(#4536-move-omit-fields-to-config)

### LINKED ISSUE #4536: move fields to omit to config
## Current behavior

in core\modules\catalog\helpers\variant\omitSelectedVariantFields.ts

two fields are hard coded to omit (just cost me 1h to figure this out^^)

`  const fieldsToOmit = ['name', 'visibility']`

## Expected behavior

in my opinion this should be moved to config 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

### PR DESCRIPTION
**Pull request by AishwaryShrivastav**
Added a config and used them instead of hard coded values.

### Related Issues

closes #4536 

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by RakowskiPrzemyslaw** [comment]
@AishwaryShrivastav please resolve conflict and change target branch to `hotfix/v1.12.2`

**Comment by AishwaryShrivastav** [comment]
> @AishwaryShrivastav please add changelog, resolve conflict and change target branch to `hotfix/v1.12.2`

Sure, I will

**Comment by RakowskiPrzemyslaw** [comment]
@AishwaryShrivastav and the branch is `hotfix/v1.12.3` it's already next version :)

**Comment by AishwaryShrivastav** [comment]
Hey @RakowskiPrzemyslaw, I have updated the branch, resolved the conflicts and added it in changelogs, please verify the Changelog.

**Pull request merged**
