### PR TITLE
#3879 Fix `CATEGORY_ADD_PRODUCTS` mutation

### LINKED ISSUE #3879: Infinite scrolling category view and `category-next/loadMoreCategoryProducts` isn't working anymore
## Current behavior

Since the fix for the category page memory-leak #3787 the infinite scrolling isn't working anymore.

Actually it's about the `CATEGORY_ADD_PRODUCTS` mutation which is called in the `category-next/loadMoreCategoryProducts` action. It lacks the changes of #3787 fix so it only adds its results to the `state` but not to the `nonReactiveState` which again leads to the problem that the `catalog-next/getCategoryProducts` getter will return `null` values for this products and drops the following error in the frontend:
```
[Vue warn]: Error in render: "TypeError: Cannot read property 'id' of undefined"

found in

---> <ProductListing> at src/themes/default/components/core/ProductListing.vue
       <LazyHydrate>
         <Category> at src/themes/default/pages/Category.vue
           <DefaultLayout> at src/themes/default/layouts/Default.vue
             <App> at src/themes/default/App.vue
               <Root>
```
## Expected behavior

The new items should be added to the `state` and `nonReactiveState` inside of the mutation.

## Steps to reproduce the issue

* Go to `src/themes/default/pages/Category.vue` and change `THEME_PAGE_SIZE` to e.g. 12
* Run VSF and go to `http://localhost:3000/women/tops-women/tops-21`
* You should only see 12 products
* You then go down the infinite scrolling wouldn't work because of an error

## Repository

Latest `release/v1.11` 5c73791cefcb6fc990d864cd5437e4793ac0725c
But caused by #3787 and 2c6e0e1c8e73952beabf550fe4530344a6bcce15

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 
- OS: OSX 
- Node: 10 LTS 
- Code Version: Latest `release/v1.11`

### PR DESCRIPTION
**Pull request by cewald**
### Related issues

closes #3879

### Short description and why it's useful

There is a bug in the `CATEGORY_ADD_PRODUCTS` mutation which causes that the infinite scrolling – or the `category-next/loadMoreCategoryProducts` action – in category list view isn't working anymore. 

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [x] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by andrzejewsky** [comment]
@cewald I think this PR https://github.com/DivanteLtd/vue-storefront/pull/3877 is exactly same, can you have look?

**Comment by cewald** [comment]
@andrzejewsky I see that in `develop` it is already done correctly: https://github.com/DivanteLtd/vue-storefront/blob/develop/core/modules/catalog-next/store/category/mutations.ts
 – I don't get when to update or to use which branch. But I will switch to use the `develop` one from now on to stay update ;)

So this branch and issue can be closed – sorry for another duplicate issue.

**Comment by cewald** [comment]
@andrzejewsky Yes it is – thanks!
PR and issue can be closed.

**Comment by andrzejewsky** [comment]
@cewald normally please use always `release` branch. Now we just merged this because of is fairly close to release and we had some changes on develop branch as well, so we wanted to merge these two branches do avoid some conflicts and also start with testing/QA upcoming 1.11 - sorry for that.

**Pull request closed without merging**
