### PR TITLE
Bugfix/Not all content is rendered after redirecting from /my-account endpoint. #3325

### LINKED ISSUE #3325: Not all content is rendered after redirecting from /my-account endpoint.
## Current behavior
When user is not logged in and tries access `/my-account` page, application refreshes itself with an error:
`vue.runtime.esm.js:1878 TypeError: Cannot read property 'image' of null`
After redirecting to home page not all components are rendered properly, there are no products in **Everything New** section in VueStorefront demo. Refershing the page solves the problem.

## Expected behavior
After redirecting all content should be rendered properly.

## Steps to reproduce the issue
1. Open https://demo.vuestorefront.io/ 
2. Go to https://demo.vuestorefront.io/my-account (when not logged in)
3. There are no products in Everything New collection.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [X] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Latest Chrome and Firefox
- OS: Ubuntu 18

### PR DESCRIPTION
**Pull request by przspa**
### Related issues

closes #3325

### Short description and why it's useful

Moved router guard to core MyAccount page mounted hook. Now Server and Client have the same code. 

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [ ] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by alinadivante** [comment]
@przspa could you remove/fix these errors from dev console?
image

**Comment by przspa** [comment]
@alinadivante fixed

**Comment by pkarw** [comment]
@przspa by some reason the CI is failing can you please check it?

**Comment by przspa** [comment]
@pkarw now everything is ok

**Pull request merged**
