### PR TITLE
Feature/improve load images on category page

### PR DESCRIPTION
**Pull request by patzick**
### Related issues

(is there any?)

### Short description and why it's useful

I've removed lazy loading from product tile, because it caused problems with blinking images.
Also alternative view was changed, because if picture was not loaded then it looked really bad.

#### Before:
before
(and with alt)
image

#### After:
after_1
(and with alt)
image

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

### CODE REVIEW

**Comment by pkarw** [comment]
Shouldn't we have the placeholders displayed instead of blank rectangles while images are being loaded? @filrak @patzick

**Comment by filrak** [comment]
we should

**Comment by filrak** [comment]
@patzick do you know why placeholder is not displayed?

**Comment by pkarw** [comment]
Guys, by this chance please test and work on the "blinking" effect which is pretty common to product and cateogry pages (images) in VS - i really hate it :) It's probably because of wrongly applied fadeIn animations

**Comment by patzick** [comment]
Guys, generally i agree with you, but now with low internet connection it looks like this:
jumping

everything is jumping, images are loaded and then v-lazy is starting by replacing image with placeholder image and then flashing back to image itself.

So rectangle block jumping content (which IMHO is really important). I've tested it with trying to set background-image with placeholder under image until it's loaded but sometimes this placeholder is loaded also after images so i think there is no gain in that.

**Comment by filrak** [comment]
Momie i think it's cool like this. You got my props

**Comment by patzick** [comment]
But wait before merging it, i'm checking option with placeholder

**Comment by patzick** [comment]
@pkarw @filrak 
now we have this effect:

aft2

**Comment by pkarw** [comment]
Let's have it set by config. Because if You've got precached images / service worker in place - generally havnig no placeholder will make much better efect (You'll get the images immediately after page refresh). Otherwise the placeholder is probably better option

OK?

**Comment by pkarw** [comment]
Second best option is to have placeholder as a background not an image. So we're not replacing the "src" but rather - displaying the images with "fastest" strategy; placeholder  OR image - depends on the image is prefetched or not

**Comment by pkarw** [comment]
OK, we've discussed it and config makes no sense

**Pull request merged**
