### PR TITLE
Unit tests for modules.ts

### LINKED ISSUE #5052: Unit tests for modules.ts
## What is the motivation for adding / enhancing this feature?

Write unit tests with 100% coverage for modules.ts

## What are the acceptance criteria 

- [x] Get 100% coverage with unit tests for core/lib/modules.ts (use yarn test:unit --coverage to check it)
- [x] Tests should be placed in core/lib/test/unit/modules.ts

## Version of Vue Storefront

- [x] Vue Storefront
- [ ] Vue Storefront Next

### PR DESCRIPTION
**Pull request by TamTran72111**
### Related Issues

closes #5052

### Short Description and Why It's Useful

This is the unit tests for `modules.ts` as the issue #5052 requires

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

-  [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
-  [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
-  [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by Fifciu — CHANGES_REQUESTED** [review]
Great job! Please update core's changelog and I will merge it

**Comment by TamTran72111** [comment]
Hi @Fifciu, Thanks for your response. I have updated the changelog.

**Comment by Fifciu** [comment]
Please resolve conflict @TamTran72111

**Comment by Fifciu** [comment]
Great, thanks a lot!

**Pull request merged**
