### PR TITLE
Feature/2985 - a.k.a "localStorage saver"

### PR DESCRIPTION
**Pull request by pkarw**
### Related issues

This is related to #2985 

### Short description and why it's useful

I've decreased the `localStorage` quota usage + error handling by introducing new config variables: 

- `config.products.disablePersistentProductsCache` to not store products by SKU (by default it's on). Products are cached in ServiceWorker cache anyway so the `product/list` will populate the in-memory cache (`cache.setItem(..., memoryOnly = true)`); 
- `config.seo.disableUrlRoutesPersistentCache` - to not store the url mappings; they're stored in in-memory cache anyway so no additional requests will be made to the backend for url mapping; however it might cause some issues with url routing in the offline mode (when the offline mode PWA installed on homescreen got reloaded, the in-memory cache will be cleared so there won't potentially be the url mappings; however the same like with `product/list` the ServiceWorker cache SHOULD populate url mappings anyway); 
- `config.syncTasks.disablePersistentTaskQueue` to not store the network requests queue in service worker. Currently only the stock-check and user-data changes were using this queue. The only downside it introuces can be related to the offline mode and these tasks will not be re-executed after connectivity established, but just in a case when the page got reloaded while offline (yeah it might happen using ServiceWorker; `syncTasks` can't be re-populated in cache from SW)

If by some reasons you wan't to have the `localStorage` back on for `Products by SKU`, `Url Routes` and `SyncTasks` - please juset set these variables back to `false` in your `config/local.json`.

### Upgrade Notes and Changelog

- [ ] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by patzick** [comment]
Looks good, i have nothing to add:)
i set label to test it by QA on branch before merge to be sure

**Comment by pkarw** [comment]
I've just changed the config property names changing the `LocalStorage` to `Persistent`. The `UniversalStorage` supports also IndexedDb, WebSQL so having LocalStorage in the property names could have been missleading

**Comment by alinadivante** [comment]
hi @pkarw I started vsf with devServiceWorkerr=true ( `yarn dev:sw` ) and comparing your branch to Demo I see that less items are now stored in Local Storage or Cache Storage (i suppose that it is OK). Please write me if I should check something else.


But please look also at this error from my dev console:
image

**Comment by pkarw** [comment]
@alinadivante thanks for testing this out! Regarding this error - it's not related to the changes included in this PR. It's the reason of "QA rejected"? :-(

**Comment by alinadivante** [comment]
@pkarw yes, it was the reason :P I didn't notice this error before, so I assumed that your changes are causing it. If not, I think the rest is fine.

**Pull request merged**
