### PR TITLE
StoreId other than 1

### PR DESCRIPTION
**Pull request by nuovecode**
### Related issues
Related to https://github.com/DivanteLtd/vue-storefront/commit/5032eb9cb64ce0f4c38d37a752d68513867d14c2#diff-53eb0dcbb2c62c8af0204c3f9aaf84fc

### Short description and why it's useful
It's just a proposal. I'm working on a store where 1 is not the default store. I think it might be a good idea to take the store id from the config rather than hard-coded it. I'm not sure this is the best solution what do you think of?

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [ ] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [ ] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by pkarw** [comment]
Irene, could You please update the changelog by this change?

**Comment by nuovecode** [comment]
Sure. In 1.9.0 or 1.10.0-rc.1?

**Comment by pkarw** [comment]
1.9 would be better :) to be released shortly

**Comment by patzick** [comment]
This is a PR with functionality from 1.10. Also PR is to develop, so definitely it should be 1.10:)
I've changed that in changelog.md. Thank you @nuovecode for improvements! :)

**Pull request merged**
