### PR TITLE
Set by default sort option and added option in configuration file

### PR DESCRIPTION
**Pull request by cnviradiya**
### Related issues

closes https://github.com/DivanteLtd/vue-storefront/issues/2935

### Short description and why it's useful

- Added option for the default sorting option in `default.json` file
- Set by default selected option in category listing page

**Here is the default.json file configuration**
`"defaultSortBy": {
        "attribute": "updated_at",
        "order": "desc"
      }`

### Screenshots of visual changes before/after (if there are any)

**Before:**
image

**After:**
image

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [ ] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [ ] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by alinadivante** [comment]
@cnviradiya I think that this solution is not enough.
Maybe it will be better to include: **Sort by:** Latest  or add arrow? What do you think about it, @StasiekDivante ?

**Comment by cnviradiya** [comment]
> @cnviradiya I think that this solution is not enough.
> image
> 
> Maybe it will be better to include: **Sort by:** Latest or add arrow? What do you think about it, @StasiekDivante ?

Yes, sure @alinadivante 
Let me add both down arrow as well as title "**Sort by**" before dropdown.

**Comment by StasiekDivante** [comment]
Yeah @alinadivante , "sort by" before dropdown is a good idea

**Comment by alinadivante** [comment]
@cnviradiya thanks!
But, could you remove "sort by" from dropdown list  ? 
image

**Comment by cnviradiya** [comment]
> @cnviradiya thanks!
> But, could you remove "sort by" from dropdown list ?
> image

Yeah sure, I can

**Comment by Jensderond** [comment]
My PR #3031 is related to some changes in this PR.

**Comment by pkarw** [comment]
@cnviradiya may I ask You to fix the conflict please?

**Comment by cnviradiya** [comment]
> @cnviradiya may I ask You to fix the conflict please?

Yeah sure @pkarw 
I'll fix soon and update you.

**Comment by cnviradiya** [comment]
> @cnviradiya may I ask You to fix the conflict please?

Hey @pkarw 
I've merged the conflict file, Please review once.

**Comment by pkarw** [comment]
Thanks!

**Pull request merged**
