### PR TITLE
Fix ecosytem config

### LINKED ISSUE #3842: SyntaxError: Unexpected Token { on v1.11 after yarn start
## Current behavior

When running `yarn start` I see the following error in pm2 logs for `server` and it fails to start:
```
40|server  | /core/scripts/server.ts:1
40|server  | import { serverHooksExecutors } from '@vue-storefront/core/server/hooks'
40|server  |        ^
40|server  |
40|server  | SyntaxError: Unexpected token {
40|server  |     at Module._compile (internal/modules/cjs/loader.js:723:23)
40|server  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
40|server  |     at Module.load (internal/modules/cjs/loader.js:653:32)
40|server  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
40|server  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
40|server  |     at Function._load (/usr/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:172:43)
40|server  |     at /usr/lib/node_modules/pm2/lib/ProcessContainer.js:295:23
40|server  |     at /usr/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16
40|server  |     at next (/usr/lib/node_modules/pm2/node_modules/async/waterfall.js:21:29)
40|server  |     at /usr/lib/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16
```
image

## Expected behavior

`yarn start` should work without errors

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: -
- OS: Linux
- Node: v10.17.0
- Code Version: release/v1.11

### PR DESCRIPTION
**Pull request by andrzejewsky**
### Related issues
closes #3842

### Which environment this relates to
- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [x] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

### Contribution and currently important rules acceptance
- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Fifciu** [comment]
@andrzejewsky Shouldn't you add `args` instead of replacing `script`?

**Comment by kristofers-magebit** [comment]
> @andrzejewsky Shouldn't you add `args` instead of replacing `script`?

This. Merged fix still gives me the same error. Adding args instead of replacing script solved the issue:
```
{
  "apps": [
    {
      "name": "server",
      "max_memory_restart": "1G",
      "instances": "4",
      "exec_mode": "cluster",
      "env": {
        "TS_NODE_PROJECT": "tsconfig-build.json",
        "NODE_ENV": "production"
      },
      "interpreter": "./node_modules/.bin/ts-node",
      "script": "./core/scripts/server.ts",
      "args": "-P ./tsconfig-build.json",
      "node_args": "--max_old_space_size=1024",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "ignore_watch": [
        "core/build/config.json",
        "node_modules"
      ]
    }
  ]
}
```

**Comment by andrzejewsky** [comment]
Ok so maybe it's worth to check, thanks @kristofers-magebit

**Comment by themreza** [comment]
@andrzejewsky I'm receiving the same error using the released version of v1.11.0 from the master branch.

**Comment by andrzejewsky** [comment]
@themreza Hey, please try with `./node_modules/.bin/pm2 install typescript` and `pm2 install typescript`

**Comment by themreza** [comment]
@andrzejewsky Thank you. I can confirm it works fine.

**Comment by pkarw** [comment]
@andrzejewsky ofc we are to fix it once and for all, right?:)

**Comment by andrzejewsky** [comment]
@pkarw actually it's not a bug in the VSF, it's the problem with pm2 - sometimes there is no TS used by pm2 that's why you have to install it - I think I can add a `postinstall` script that will run mentioned command

**Comment by pkarw** [comment]
Ok, I have thought on this kind of solution actually!

**Comment by themreza** [comment]
@andrzejewsky It's weird. After restarting the server the same error has reappeared.
Running the `pm2 install typescript` doesn't seem to fix it anymore.
Using `yarn start:inspect` works fine, but not `yarn start`.

By the way, PM2's website suggests not to use this method. Any other workarounds?
> We highly don’t recommend to use this in production as it slows down your app. In that case, your app must be bundled i.e. transpiled from the source to get a pre-processed version of your app.
https://doc.pm2.io/en/runtime/integration/transpilers/

**Comment by andrzejewsky** [comment]
@themreza  In that case, I think we need to bundle server.ts and run it without TS that will be the best solution - I'll create an issue for that

**Pull request merged**
