### PR TITLE
Adds storeCode to formatCategoryLink method

### PR DESCRIPTION
**Pull request by michasik**
### Related issues
Additional fix, for this issue: #2987
Related PR: #3038, https://github.com/DivanteLtd/vue-storefront/pull/3154

### Short description and why it's useful
When <code>multistore</code> was set to true in <code>local.json</code> the category links did not preserve the <code>storeCode</code>. Now whenever the user switches between categories from the menu the <code>storeCode</code> is preserved.

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [ ] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [ ] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by patzick** [comment]
@michasik this kind of helpers are extremly important, so should have unit tests. To show you how to test that kind of helpers i added example. Please fill it at least with cases (in both scenarios with and without urlDispatcher):
- [ ] no category
- [ ] different default storeCode in storeView
- [ ] null storecode as helper param
- [ ] another storecode as helper param
- [ ] empty storecode string as helper parem
- [ ] more if you'll find cases...:)

with this approach, with describe for big cases, we have very clear test error message:
```
formatCategoryLink method › with active urlDispatcher › should return formatted category url_path
    Expected: "/all-2/women/women-202"
    Received: "/all-2/women/women-20"
```
i did that error in test to show how nice it could look and how easy is later to catch errors, please change that during improvement :)

cc: @pkarw, @filrak - guys please also take a look and analyze that

**Comment by pkarw** [comment]
Looks, cool with the tests. @michasik you've put "WIP" by the tests commit. Is it it ready to be merged in?

**Comment by michasik** [comment]
@pkarw It is not ready yet, there are at least two cases still to cover.

**Comment by michasik** [comment]
@pkarw  @patzick 
Hi guys, can you have a look at the the tests and the formatCategoryLink method itself?
If it's fine with you it's ready to be merged.

**Pull request merged**
