### PR TITLE
es7 support

### PR DESCRIPTION
**Pull request by andrzejewsky**
### Related issues
related https://github.com/DivanteLtd/vue-storefront-api/pull/342

### Which environment this relates to
- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [x] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

### Contribution and currently important rules acceptance
- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pkarw** [comment]
@andrzejewsky yeah, exactly this. But it should be conditional statement to support prev. Elastic versions as well

**Comment by andrzejewsky** [comment]
@pkarw done

**Comment by ajsit** [comment]
You havnt addressed the breaking changes issue for Elastic 7, _sourceInclude and _sourceExclude is deprecated and requires the plural form now.

**Comment by andrzejewsky** [comment]
@ajsit we are still working on ES7 integration, planned to be released in `1.11`. This PR fixes common issues that we've found, but the PR that introduces ES7 in the API has not merged yet as it requires more tests. When it comes to breaking changes - we'd like to support both ES5 and ES7 without BC-breaks for end user/developer as it could be possible so probably these name for VSF perspective will be still same - will see, otherwise we put some upgrade notes. 

Thanks for comment 👍

**Pull request merged**
