### PR TITLE
Add storeId to user/register call

### LINKED ISSUE #4613: Add the website_id to the user/register call
## What is the motivation for adding / enhancing this feature?

Reference/discussion: https://github.com/DivanteLtd/vue-storefront/issues/3848

We need to add the `website_id` to be configurable via: `config.storeViews.*.website_id` and then passed via the JSON body to `vue-storefront-api`/`storefront-api`. Then we need to pass this very same information to the magento instance. So probably a minor change to https://github.com/DivanteLtd/magento would be required

## What are the acceptance criteria 

- [ ] `website_id` is configurable in the config.storeViews
- [ ] `website_id` is supported by the user/register call

### PR DESCRIPTION
**Pull request by haelbichalex**
### Related Issues

closes #4613 

### Short Description and Why It's Useful

Because of unknown reasons Magento created users in the default website, even though the request was sent to the correct url. This PR adds the `storeId` to the `user/register` call, which instructs Magento to create the customer in the given store.

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [x] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by gibkigonzo** [comment]
@haelbichalex can you move changelog to 1.12.3 section?

**Comment by haelbichalex** [comment]
@gibkigonzo Done

**Comment by simonmaass** [comment]
@haelbichalex @gibkigonzo this also needs to be fixed in core\modules\checkout\components\OrderReview.ts

**Comment by simonmaass** [comment]
weird.. after including fix the following test fails:

```
FAIL core/modules/checkout/test/unit/components/OrderReview.spec.ts
  ● Test suite failed to run
    TypeError: (0 , _helpers.once) is not a function
      16 | }
      17 |
    > 18 | once('__VUE_EXTEND_DROPPOINT_VPB__', () => {
         | ^
      19 |   Vue.use(VueProgressBar, optionsBar)
      20 | })
      21 |
      at Object.<anonymous> (src/themes/craftsoles/index.js:18:1)
      at Object.<anonymous> (core/app.ts:16:1)
      at Object.<anonymous> (core/modules/url/helpers/index.ts:1:1)
      at Object.<anonymous> (core/helpers/index.ts:3:1)
      at Object.<anonymous> (core/store/index.ts:4:1)
      at Object.<anonymous> (core/lib/multistore.ts:1:1)
      at Object.<anonymous> (core/modules/checkout/components/OrderReview.ts:4:1)
      at Object.<anonymous> (core/modules/checkout/test/unit/components/OrderReview.spec.ts:2:1)
```

any idea why including:

import { currentStoreView } from '@vue-storefront/core/lib/multistore'

lets the test fail?

**Pull request merged**
