### PR TITLE
ref. #956 replace all #333 colors to #4F4F4F

### PR DESCRIPTION
**Pull request by lorenaramonda**
Notice: pay attention that this may disable color change effects on hovering some element, especially those that use primary color variables as now they're the same in both statuses:

primary: (
default: map-get($colors, matterhorn),
hover: map-get($colors, matterhorn)
),

matterhorn is #4F4F4F

(this is the right PR, I hope! thanks @pkarw for the patience!)

### CODE REVIEW

**Comment by pkarw** [comment]
@StasiekDivante could you check the hovers - as Lori they disappear after this change and I’m not sure if that’s expected effect?

**Comment by StasiekDivante** [comment]
@lorenaramonda that's one good point, haven't noticed that

By color replacement I meant replacement in font colors - headers, link etc
Thanks for staying attentive!

**Comment by pkarw** [comment]
@lorenaramonda could you just adjust this change to not cover the elements that have some hover effect?

**Comment by lorenaramonda** [comment]
Yes @pkarw sure. I'll have a check!

**Comment by lorenaramonda** [comment]
Now it should have been replaced where needed. The change also affected the .notification.info class in src/themes/catalog/components/core/Notification.vue. Please, check that this is the desiderata.

**Comment by pkarw** [comment]
Thanks!

**Pull request merged**
