### PR TITLE
Webpack config improvements

### PR DESCRIPTION
**Pull request by DavidRouyer**

### CODE REVIEW

**Comment by pkarw** [comment]
@DavidRouyer could You please check the build error - https://travis-ci.org/DivanteLtd/vue-storefront/jobs/387045204
?

**Comment by DavidRouyer** [comment]
It seems the config.json file is not generated in core\build :/

**Comment by pkarw** [comment]
Ok, I’ll check it and merge in after you fix the issue with generating build/config.json (however I don’t see at first glance how these changes could broke it :)). For sure these changes are a way to go

**Comment by pkarw** [comment]
ElasticSearch is used just in the core/lib/search.js and we’re using very basic stuff - just sending out the query/getting back the results. As we’re using bodybuilder to create elastic query (https://bodybuilder.js.org/docs/) You can probably just remove the ElasticSearch and user fetch() instead

**Comment by filrak** [comment]
@DavidRouyer how the things are going with this task? ;)

**Comment by filrak** [comment]
@DavidRouyer can you change the target branch to develop?

**Pull request merged**
