### PR TITLE
Feature/mac os and linux installation

### PR DESCRIPTION
**Pull request by madonzy**

### CODE REVIEW

**Comment by pkarw** [comment]
@madonzy almost there but problem at the last step!

Here you have logs:

```
Trying change directory to '/private/tmp/installer-test/vue-storefront'... 

 Working in directory '/private/tmp/installer-test/vue-storefront'... 

 Creating storefront config 'src/config.json'... 

 Build storefront npm... 
/bin/sh: $1: ambiguous redirect
┌───────────────────────────────────────────────────────────────────────────────────────────────────┐
│ ERROR                                                                                             │
│                                                                                                   │
│ Can't build storefront npm.                                                                       │
│                                                                                                   │
│ Please check log file for details: /private/tmp/installer-test/vue-storefront/var/log/install.log │
└───────────────────────────────────────────────────────────────────────────────────────────────────┘

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-storefront@0.0.0 install: `node install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-storefront@0.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pkarwatka/.npm/_logs/2017-11-06T19_30_31_783Z-debug.log
MacBook-Pro-Piotr-2:vue-storefront pkarwatka$ cat /private/tmp/installer-test/vue-storefront/var/log/install.log
Cloning into '../vue-storefront-api'...
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> fsevents@1.1.2 install /private/tmp/installer-test/vue-storefront-api/node_modules/fsevents
> node install

[fsevents] Success: "/private/tmp/installer-test/vue-storefront-api/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm notice created a lockfile as package-lock.json. You should commit this file.
added 811 packages in 17.644s

> vue-storefront-api@0.1.0 restore /private/tmp/installer-test/vue-storefront-api
> node node_modules/elasticdump/bin/elasticdump --input=var/catalog.json --output=http://localhost:9200/vue_storefront_catalog

Mon, 06 Nov 2017 19:28:22 GMT | starting dump
Mon, 06 Nov 2017 19:28:22 GMT | got 100 objects from source file (offset: 0)
Mon, 06 Nov 2017 19:28:23 GMT | sent 100 objects to destination elasticsearch, wrote 100
Mon, 06 Nov 2017 19:28:23 GMT | got 122 objects from source file (offset: 100)
Mon, 06 Nov 2017 19:28:24 GMT | sent 122 objects to destination elasticsearch, wrote 122
Mon, 06 Nov 2017 19:28:24 GMT | got 108 objects from source file (offset: 222)
Mon, 06 Nov 2017 19:28:25 GMT | sent 108 objects to destination elasticsearch, wrote 108
Mon, 06 Nov 2017 19:28:25 GMT | got 120 objects from source file (offset: 330)
Mon, 06 Nov 2017 19:28:25 GMT | sent 120 objects to destination elasticsearch, wrote 120
Mon, 06 Nov 2017 19:28:25 GMT | got 117 objects from source file (offset: 450)
Mon, 06 Nov 2017 19:28:26 GMT | sent 117 objects to destination elasticsearch, wrote 117
Mon, 06 Nov 2017 19:28:26 GMT | got 126 objects from source file (offset: 567)
Mon, 06 Nov 2017 19:28:26 GMT | sent 126 objects to destination elasticsearch, wrote 126
Mon, 06 Nov 2017 19:28:26 GMT | got 101 objects from source file (offset: 693)
Mon, 06 Nov 2017 19:28:27 GMT | sent 101 objects to destination elasticsearch, wrote 101
Mon, 06 Nov 2017 19:28:27 GMT | got 116 objects from source file (offset: 794)
Mon, 06 Nov 2017 19:28:27 GMT | sent 116 objects to destination elasticsearch, wrote 116
Mon, 06 Nov 2017 19:28:27 GMT | got 104 objects from source file (offset: 910)
Mon, 06 Nov 2017 19:28:27 GMT | sent 104 objects to destination elasticsearch, wrote 104
Mon, 06 Nov 2017 19:28:27 GMT | got 108 objects from source file (offset: 1014)
Mon, 06 Nov 2017 19:28:27 GMT | sent 108 objects to destination elasticsearch, wrote 108
Mon, 06 Nov 2017 19:28:27 GMT | got 122 objects from source file (offset: 1122)
Mon, 06 Nov 2017 19:28:28 GMT | sent 122 objects to destination elasticsearch, wrote 122
Mon, 06 Nov 2017 19:28:28 GMT | got 119 objects from source file (offset: 1244)
Mon, 06 Nov 2017 19:28:28 GMT | sent 119 objects to destination elasticsearch, wrote 119
Mon, 06 Nov 2017 19:28:28 GMT | got 113 objects from source file (offset: 1363)
Mon, 06 Nov 2017 19:28:28 GMT | sent 113 objects to destination elasticsearch, wrote 113
Mon, 06 Nov 2017 19:28:28 GMT | got 102 objects from source file (offset: 1476)
Mon, 06 Nov 2017 19:28:28 GMT | sent 102 objects to destination elasticsearch, wrote 102
Mon, 06 Nov 2017 19:28:28 GMT | got 105 objects from source file (offset: 1578)
Mon, 06 Nov 2017 19:28:29 GMT | sent 105 objects to destination elasticsearch, wrote 105
Mon, 06 Nov 2017 19:28:29 GMT | got 122 objects from source file (offset: 1683)
Mon, 06 Nov 2017 19:28:29 GMT | sent 122 objects to destination elasticsearch, wrote 122
Mon, 06 Nov 2017 19:28:29 GMT | got 106 objects from source file (offset: 1805)
Mon, 06 Nov 2017 19:28:29 GMT | sent 106 objects to destination elasticsearch, wrote 106
Mon, 06 Nov 2017 19:28:29 GMT | got 110 objects from source file (offset: 1911)
Mon, 06 Nov 2017 19:28:29 GMT | sent 110 objects to destination elasticsearch, wrote 110
Mon, 06 Nov 2017 19:28:29 GMT | got 118 objects from source file (offset: 2021)
Mon, 06 Nov 2017 19:28:30 GMT | sent 118 objects to destination elasticsearch, wrote 118
Mon, 06 Nov 2017 19:28:30 GMT | got 0 objects from source file (offset: 2139)
Mon, 06 Nov 2017 19:28:30 GMT | Total Writes: 2139
Mon, 06 Nov 2017 19:28:30 GMT | dump complete

> vue-storefront-api@0.1.0 migrate /private/tmp/installer-test/vue-storefront-api
> node node_modules/migrate/bin/migrate

Elasticsearch INFO: 2017-11-06T19:28:32Z
  Adding connection to http://localhost:9200/

  up : 1506760343216-example-products.js
Elasticsearch DEBUG: 2017-11-06T19:28:32Z
  starting request {
    "method": "POST",
    "path": "/vue_storefront_catalog/product/99999/_create",
    "body": {
      "id": 22,
      "sku": "24-WG088",
      "name": "Sprite Foam Roller",
      "attribute_set_id": 11,
      "price": 19,
      "status": 1,
      "visibility": 4,
      "type_id": "simple",
      "created_at": "2017-09-16 13:46:47",
      "updated_at": "2017-09-16 13:46:47",
      "extension_attributes": [],
      "product_links": [],
      "tier_prices": [],
      "custom_attributes": null,
      "category": [
        {
          "category_id": 2,
          "name": "Default Category"
        },
        {
          "category_id": 3,
          "name": "Gear"
        },
        {
          "category_id": 5,
          "name": "Fitness Equipment"
        }
      ],
      "tsk": 1505573582376,
      "description": "<p>It hurts so good to use the Sprite Foam Roller on achy, tired muscles for myofascial massage therapy. Or you can add this fundamental piece to your Pilates and yoga accouterment, or apply towards core stability, strengthening and balance exercise. </p>\n<ul>\n<li>6'' wide by 12'' long.</li>\n<li>Safe for myofascial release.</li>\n<li>EPP or PE foam options.</li>\n<li>Solid, dense, closed-cell foam.</li>\n</ul>",
      "image": "/l/u/luma-foam-roller.jpg",
      "small_image": "/l/u/luma-foam-roller.jpg",
      "thumbnail": "/l/u/luma-foam-roller.jpg",
      "options_container": "container2",
      "required_options": "0",
      "has_options": "0",
      "url_key": "sprite-foam-roller",
      "tax_class_id": "2",
      "activity": "8,11",
      "material": "42",
      "gender": "80,81,84",
      "category_gear": "87"
    },
    "query": {}
  }
  

Elasticsearch DEBUG: 2017-11-06T19:28:33Z
  Request complete

Elasticsearch DEBUG: 2017-11-06T19:28:33Z
  starting request {
    "method": "DELETE",
    "path": "/vue_storefront_catalog/product/99999",
    "query": {}
  }
  

Elasticsearch DEBUG: 2017-11-06T19:28:33Z
  Request complete

  up : 1506761965798-example-put-mapping.js
Elasticsearch DEBUG: 2017-11-06T19:28:33Z
  starting request {
    "method": "PUT",
    "path": "/vue_storefront_catalog/_mapping/product",
    "body": {
      "properties": {
        "slug": {
          "type": "string"
        },
        "suggest": {
          "type": "completion",
          "analyzer": "simple",
          "search_analyzer": "simple"
        }
      }
    },
    "query": {}
  }
  

Elasticsearch DEBUG: 2017-11-06T19:28:33Z
  Request complete

{ acknowledged: true }
  up : 1506763059112-example-get-mapping.js
Elasticsearch DEBUG: 2017-11-06T19:28:33Z
  starting request {
    "method": "GET",
    "path": "/vue_storefront_catalog/_mapping/product",
    "query": {}
  }
  

Elasticsearch DEBUG: 2017-11-06T19:28:33Z
  Request complete

{ vue_storefront_catalog1507151193738: 
   { mappings: 
      { product: 
         { properties: 
            { activity: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              attribute_set_id: { type: 'long' },
              aw_arp_override_native: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              category: 
               { properties: 
                  { category_id: { type: 'long' },
                    name: 
                     { type: 'text',
                       fields: { keyword: { type: 'keyword', ignore_above: 256 } } } } },
              category_gear: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              category_ids: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              children_data: 
               { properties: 
                  { name: 
                     { type: 'text',
                       fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
                    price: { type: 'long' },
                    sku: 
                     { type: 'text',
                       fields: { keyword: { type: 'keyword', ignore_above: 256 } } } } },
              climate: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              color: { type: 'integer' },
              configurable_children: 
               { properties: 
                  { custom_attributes: 
                     { properties: 
                        { attribute_code: 
                           { type: 'text',
                             fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
                          value: 
                           { type: 'text',
                             fields: { keyword: { type: 'keyword', ignore_above: 256 } } } } },
                    name: 
                     { type: 'text',
                       fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
                    price: { type: 'long' },
                    sku: 
                     { type: 'text',
                       fields: { keyword: { type: 'keyword', ignore_above: 256 } } } } },
              configurable_options: 
               { properties: 
                  { attribute_id: 
                     { type: 'text',
                       fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
                    id: { type: 'long' },
                    label: 
                     { type: 'text',
                       fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
                    position: { type: 'long' },
                    product_id: { type: 'long' },
                    values: { properties: { value_index: { type: 'long' } } } } },
              created_at: 
               { type: 'date',
                 format: 'yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis' },
              custom_design_from: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              description: { type: 'text' },
              eco_collection: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              erin_recommends: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              features_bags: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              format: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              gender: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              gift_message_available: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              has_options: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              id: { type: 'integer' },
              image: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              links_purchased_separately: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              links_title: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              material: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              meta_description: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              msrp_display_actual_price_type: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              name: { type: 'text' },
              new: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              news_from_date: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              options_container: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              pattern: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              performance_fabric: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              pl_size_chart: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              price: { type: 'double' },
              price_type: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              price_view: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              query: 
               { properties: 
                  { match: 
                     { properties: 
                        { name: 
                           { type: 'text',
                             fields: { keyword: { type: 'keyword', ignore_above: 256 } } } } } } },
              required_options: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              sale: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              samples_title: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              shipment_type: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              short_description: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              size: { type: 'integer' },
              sku: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              sku_type: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              slug: { type: 'text' },
              small_image: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              special_from_date: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              special_price: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              status: { type: 'integer' },
              stock: 
               { properties: 
                  { backorders: { type: 'long' },
                    enable_qty_increments: { type: 'boolean' },
                    is_decimal_divided: { type: 'boolean' },
                    is_in_stock: { type: 'boolean' },
                    is_qty_decimal: { type: 'boolean' },
                    item_id: { type: 'long' },
                    manage_stock: { type: 'boolean' },
                    max_sale_qty: { type: 'long' },
                    min_qty: { type: 'long' },
                    min_sale_qty: { type: 'long' },
                    notify_stock_qty: { type: 'long' },
                    product_id: { type: 'long' },
                    qty: { type: 'long' },
                    qty_increments: { type: 'long' },
                    show_default_notification_message: { type: 'boolean' },
                    stock_id: { type: 'long' },
                    stock_status_changed_auto: { type: 'long' },
                    use_config_backorders: { type: 'boolean' },
                    use_config_enable_qty_inc: { type: 'boolean' },
                    use_config_manage_stock: { type: 'boolean' },
                    use_config_max_sale_qty: { type: 'boolean' },
                    use_config_min_qty: { type: 'boolean' },
                    use_config_min_sale_qty: { type: 'long' },
                    use_config_notify_stock_qty: { type: 'boolean' },
                    use_config_qty_increments: { type: 'boolean' } } },
              strap_bags: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              style_bags: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              style_bottom: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              style_general: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              suggest: 
               { type: 'completion',
                 analyzer: 'simple',
                 preserve_separators: true,
                 preserve_position_increments: true,
                 max_input_length: 50 },
              tax_class_id: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              thumbnail: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              tsk: { type: 'long' },
              type_id: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              updated_at: 
               { type: 'date',
                 format: 'yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis' },
              url_key: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } },
              visibility: { type: 'integer' },
              weight: { type: 'integer' },
              weight_type: 
               { type: 'text',
                 fields: { keyword: { type: 'keyword', ignore_above: 256 } } } } } } } }
  up : 1507147503759-change-size-color.js
Elasticsearch DEBUG: 2017-11-06T19:28:33Z
  starting request {
    "method": "PUT",
    "path": "/vue_storefront_catalog1509996513303",
    "query": {}
  }
  

Elasticsearch DEBUG: 2017-11-06T19:28:34Z
  Request complete

Elasticsearch DEBUG: 2017-11-06T19:28:34Z
  starting request {
    "method": "PUT",
    "path": "/vue_storefront_catalog1509996513303/_mapping/product",
    "body": {
      "properties": {
        "size": {
          "type": "integer"
        },
        "price": {
          "type": "double"
        },
        "color": {
          "type": "integer"
        },
        "pattern": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "status": {
          "type": "integer"
        },
        "weight": {
          "type": "integer"
        },
        "visibility": {
          "type": "integer"
        },
        "created_at": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        },
        "updated_at": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        },
        "description": {
          "type": "text"
        },
        "name": {
          "type": "text"
        }
      }
    },
    "query": {}
  }
  

Elasticsearch DEBUG: 2017-11-06T19:28:34Z
  Request complete

{ acknowledged: true }
Elasticsearch DEBUG: 2017-11-06T19:28:34Z
  starting request {
    "method": "POST",
    "path": "/_reindex",
    "body": {
      "source": {
        "index": "vue_storefront_catalog"
      },
      "dest": {
        "index": "vue_storefront_catalog1509996513303"
      }
    },
    "query": {}
  }
  

Elasticsearch DEBUG: 2017-11-06T19:28:38Z
  Request complete

Elasticsearch DEBUG: 2017-11-06T19:28:38Z
  starting request {
    "method": "DELETE",
    "path": "/vue_storefront_catalog",
    "query": {}
  }
  

Elasticsearch DEBUG: 2017-11-06T19:28:38Z
  Request complete

{ acknowledged: true }
Elasticsearch DEBUG: 2017-11-06T19:28:38Z
  starting request {
    "method": "PUT",
    "path": "/vue_storefront_catalog1509996513303/_alias/vue_storefront_catalog",
    "query": {}
  }
  

  migration : complete
Cloning into 'var/magento2-sample-data'...
MacBook-Pro-Piotr-2:vue-storefront pkarwatka$ 
```

**Comment by pkarw** [comment]
... one more thing - when going with default images backend (demo.vuestorefront.io) - trailing slash is missed in the path so in the end images are not loading properly:
https://www.dropbox.com/s/c4weqq7l8qglgv0/Zrzut%20ekranu%202017-11-06%2020.33.11.png?dl=0

**Comment by pkarw** [comment]
Despite this 2 problems, after running "npm run dev" site was up and running!

**Comment by pkarw** [comment]
One more important thing. In the config.json within `vue-storefront-api` you should fill out:

```
    "whitelist": {
      "allowedHosts": [
        ".*divante.pl"
      ],
      "trustedHosts": [
        ".*divante.pl"
      ]

```

with the domain names of currently used images backend (for example demo.vuestorefront.io or localhost) - otherwise image proxy wont work

test URL: http://localhost:8080/img/310/300/resize/m/h/mh13-blue_main.jpg

If config is set not properly - this url will not finish loading (hang up) :) If it's fine - you'll see beatufull product picture

**Comment by pkarw** [comment]
ig system is linux or macosx and there is "imagemagick" installed, the default image backend should be localhost:8080/img -> because image proxy WILL work with this configuration (on windows machines we should use demo.vuestorefront.io/img because most windows users doesn't have imagemagick installed)

**Comment by madonzy** [comment]
@pkarw npm error was fixed, image endpoint path now has a slash (filter was added), domain now is adding to allowed and trusted hosts ;)

**Pull request merged**
