### PR TITLE
[Docs] Old doc folder removed

### PR DESCRIPTION
**Pull request by NataliaTepluhina**
1. Removed `doc` folder
2. Changed `README` to have images/links/etc. from the new docs folder
3. Added `stylesheets` doc.
4. Removed sync state.

### CODE REVIEW

**Comment by filrak** [comment]
Perfect ! Thanks Natalia!
Is it ready to merge in?

**Comment by pkarw** [comment]
I've  checked the removed files and it seems that we're missing the following - still quite accurate docs:
- doc/E2E tests.md
- doc/Extending vue-storefront-api.md
- doc/Extending Express.js server side routes.md
- doc/Payment Gateway Integration.md
- doc/Upgrade notes.md

@NataliaTepluhina I think these docs are pretty important, can You just move them to the new structure so we could remove /doc once and for all?

**Comment by NataliaTepluhina** [comment]
@pkarw working on it

**Comment by NataliaTepluhina** [comment]
@pkarw Please review latest changes

**Comment by pkarw** [comment]
After adding basic docs about modules we are ready to merge this in - I’ve checked the rest and seeems fine

**Comment by NataliaTepluhina** [comment]
@pkarw done :)

**Pull request merged**
