### PR TITLE
Possible solution for docker-compose up hanging on Windows installation

### PR DESCRIPTION
**Pull request by andrewyin1994**
### Related issues

docker-compose up hanging during Windows installation (though it was waiting, not hanging)

### Short description and why it's useful

I'm not too good with terminology, but this was what I did to get through the setup when it seemed like docker was hanging (which it actually wasn't; it was waiting for activity on the actual website). This may not be a real problem for developers who are familiar with Docker or developing on Windows, but I am a new developer and this was very frustrating for me to get past.

### CODE REVIEW

**Comment by filrak** [comment]
@mdanilowicz @pkarw can you review

**Comment by pkarw** [comment]
OK I'll merge this in however it doesn't sound like a final solution to this matter :)

**Comment by pkarw** [comment]
OK I'll merge this in however it doesn't sound like a final solution to this matter :)

**Comment by pkarw** [comment]
OK I'll merge this in however it doesn't sound like a final solution to this matter :)

**Pull request merged**
