### PR TITLE
Remove vue-lazyload

### LINKED ISSUE #4998: Remove vue-lazyload from core
## What is the motivation for adding / enhancing this feature?

We should not load vue-lazyload in core file, because:

* we can't change vue-lazyload options (for example I can't add path for loading or error state images)
* we don't have alternative (for example in capybara we use sfui which uses different lib. In result we load two libs)

## What are the acceptance criteria 

* [ ] - removed vue-lazyload from core
* [ ] - added vue-lazyload in default theme main file (from https://github.com/DivanteLtd/vue-storefront/blob/master/core/app.ts#L69 to https://github.com/DivanteLtd/vsf-default/blob/master/index.js#L19)

## Version of Vue Storefront

* [x] Vue Storefront
* [ ] Vue Storefront Next

## Can you complete this feature request by yourself?
* [x] YES
* [ ] NO

### PR DESCRIPTION
**Pull request by jahvi**
### Related Issues

closes #4998 

### Short Description and Why It's Useful

Remove vue-lazyload dependency from core as it's only used in the theme level.

Related PR in `vsf-default`: https://github.com/DivanteLtd/vsf-default/pull/36

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by gibkigonzo** [comment]
Please add info about it in upgrade notes https://github.com/DivanteLtd/vue-storefront/blob/master/docs/guide/upgrade-notes/README.md (you need to create new section for 1.13)

**Comment by jahvi** [comment]
Done, I wasn't sure about the wording but let me know if you want me to change it.

**Review by Fifciu — APPROVED** [review]

**Comment by Fifciu** [comment]
Please resolve conflict @jahvi

**Comment by jahvi** [comment]
Should be done now

**Pull request merged**
