### PR TITLE
Fix images blend mode css bug for some Android With Chrome Webview

### PR DESCRIPTION
**Pull request by pmaojo**

### CODE REVIEW

**Comment by pkarw** [comment]
Please do update the changelog and this is good to go

**Comment by pkarw** [comment]
Please also do review other instances of mix-blend multiply (for example ProductGallery)

**Comment by pmaojo** [comment]
@pkarw 
I will review other instances and update changelog.

**Comment by pmaojo** [comment]
@pkarw is this deployed?

**Comment by pkarw** [comment]
Hi there! No it's not yet deployed

**Comment by pmaojo** [comment]
@pkarw I didn't finish the review of other elements and changelog

**Comment by pkarw** [comment]
Yeah, i know :-) we did - the only missing part was the changelog. Please feel free to update it in the next PR

**Pull request merged**
