### PR TITLE
fix applying 'is_user_defined' and 'is_visible' in createAttributesListQuery

### PR DESCRIPTION
**Pull request by gibkigonzo**
### Short Description and Why It's Useful

Right now when we make search for attributes we build invalid query (`createAttributesListQuery`). `'is_user_defined'` and `'is_visible'` can also have `'1'` as value, not only `true`.

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [x] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [x] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by flancer64** [comment]
I have an error 
```
{
  "type": "illegal_argument_exception",
  "reason": "Can't parse boolean value [1], expected [true] or [false]"
}
```

for query (Elasticsearch version: "7.6.1"):
```
{
  "bool": {
    "filter": [
      {
        "bool": {
          "must": [
            {
              "terms": {
                "attribute_code": ["..."],
                "boost": 1.0
              }
            },
            {
              "terms": {
                "is_user_defined": [true, "1"],
                "boost": 1.0
              }
            },
            {
              "terms": {
                "is_visible": [true, "1"],
                "boost": 1.0
              }
            }
          ],
          "adjust_pure_negative": true,
          "boost": 1.0
        }
      }
    ],
    "adjust_pure_negative": true,
    "boost": 1.0
  }
}
```

This is data types mapping for my index of attributes:
```
{
  "mappings": {
    "_doc": {
      "properties": {
        "frontend_label": {"type": "text", "fields": {"keyword": {"ignore_above": 256, "type": "keyword"}}},
        "is_visible": {"type": "boolean"},
        "is_visible_on_front": {"type": "boolean"},
        "attribute_id": {"type": "long"},
        "options": {
          "properties": {
            "label": {"type": "text", "fields": {"keyword": {"ignore_above": 256, "type": "keyword"}}},
            "value": {"type": "text"}
          }
        },
        "id": {"type": "long"},
        "frontend_input": {"type": "text", "fields": {"keyword": {"ignore_above": 256, "type": "keyword"}}},
        "is_user_defined": {"type": "boolean"},
        "attribute_code": {"type": "text", "fields": {"keyword": {"ignore_above": 256, "type": "keyword"}}},
        "is_comparable": {"type": "boolean"}
      }
    }
  }
}
```

I'm nub in Elasticsearch, probably there is some configuration option to ignore data types in queries but I don't know. Just share my case.

**Comment by flancer64** [comment]
I see that Elasticsearch version 5.6 [allows](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/boolean.html) different values for `boolean`:
```
False values | false, "false", "off", "no", "0", "" (empty string), 0, 0.0
-- | --
True values | Anything that isn’t false.
```

but version 6.0 and above [don't](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/boolean.html):
```
False values | false, "false"
-- | --
True values | true, "true"
```

I suppose we should revert these changes or make query more smart (add ES version dependency).

**Comment by mwalol** [comment]
hi,

i'm using elasticsearch 7.3 and i had to change : 

```
  if (onlyDefinedByUser) {
    searchQuery = searchQuery.applyFilter({ key: 'is_user_defined', value: { 'in': [true] } })
  }
  if (onlyVisible) {
    searchQuery = searchQuery.applyFilter({ key: 'is_visible', value: { 'in': [true] } })
  }
```

instead of [true, '1'] to fix the issue

**Comment by SDLyu** [comment]
Hi @gibkigonzo 
This is not working in ElasticSearch 7. 
I get error 

```
{
  "type": "illegal_argument_exception",
  "reason": "Can't parse boolean value [1], expected [true] or [false]"
}
```

**Comment by gepdev** [comment]
> Hi @gibkigonzo
> This is not working in ElasticSearch 7.
> I get error
> 
> ```
> {
>   "type": "illegal_argument_exception",
>   "reason": "Can't parse boolean value [1], expected [true] or [false]"
> }
> ```

I have the same error with ES 7

**Pull request merged**
